// Auto-generated by tools/gen_colloquial_data.py — do not edit by hand.
// Character + pinyin from Jun Da's frequency list; examples hand-authored,
// example pinyin produced with pypinyin (tone marks).
window.COLLOQUIAL_DATA = [
  {
    "rank": 1,
    "c": "的",
    "py": "de",
    "en": "of; 's (possessive particle)",
    "ex": "这是我的手机。",
    "exPy": "zhè shì wǒ de shǒu jī.",
    "exEn": "This is my phone."
  },
  {
    "rank": 2,
    "c": "一",
    "py": "yī",
    "en": "one",
    "ex": "我要一杯咖啡。",
    "exPy": "wǒ yào yì bēi kā fēi.",
    "exEn": "I want one coffee.",
    "tone": "Tone change: 一 is yī alone or in numbers/dates, yí before a 4th tone, yì before 1st/2nd/3rd tones — here 一杯 is yì bēi."
  },
  {
    "rank": 3,
    "c": "是",
    "py": "shì",
    "en": "to be; yes",
    "ex": "我是学生。",
    "exPy": "wǒ shì xué shēng.",
    "exEn": "I am a student."
  },
  {
    "rank": 4,
    "c": "不",
    "py": "bù",
    "en": "not; no",
    "ex": "我不知道。",
    "exPy": "wǒ bù zhī dào.",
    "exEn": "I don't know.",
    "tone": "Tone change: 不 becomes bú before a 4th tone, otherwise bù — here 不知 is bù zhī."
  },
  {
    "rank": 5,
    "c": "了",
    "py": "le",
    "en": "(completed action / change particle)",
    "ex": "我吃了。",
    "exPy": "wǒ chī le.",
    "exEn": "I've eaten."
  },
  {
    "rank": 6,
    "c": "在",
    "py": "zài",
    "en": "at; in; -ing (progressive)",
    "ex": "我在家。",
    "exPy": "wǒ zài jiā.",
    "exEn": "I'm at home."
  },
  {
    "rank": 7,
    "c": "人",
    "py": "rén",
    "en": "person; people",
    "ex": "他是好人。",
    "exPy": "tā shì hǎo rén.",
    "exEn": "He's a good person."
  },
  {
    "rank": 8,
    "c": "有",
    "py": "yǒu",
    "en": "to have; there is",
    "ex": "你有时间吗？",
    "exPy": "nǐ yǒu shí jiān ma?",
    "exEn": "Do you have time?"
  },
  {
    "rank": 9,
    "c": "我",
    "py": "wǒ",
    "en": "I; me",
    "ex": "我很好。",
    "exPy": "wǒ hěn hǎo.",
    "exEn": "I'm doing well.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 我很 is written wǒ hěn but said wó hěn."
  },
  {
    "rank": 10,
    "c": "他",
    "py": "tā",
    "en": "he; him",
    "ex": "他在哪儿？",
    "exPy": "tā zài nǎr?",
    "exEn": "Where is he?"
  },
  {
    "rank": 11,
    "c": "这",
    "py": "zhè",
    "en": "this",
    "ex": "这个多少钱？",
    "exPy": "zhè ge duō shǎo qián?",
    "exEn": "How much is this?"
  },
  {
    "rank": 12,
    "c": "个",
    "py": "gè",
    "en": "(general measure word)",
    "ex": "给我一个。",
    "exPy": "gěi wǒ yí gè.",
    "exEn": "Give me one."
  },
  {
    "rank": 13,
    "c": "们",
    "py": "men",
    "en": "(plural marker for pronouns/people)",
    "ex": "你们好！",
    "exPy": "nǐ men hǎo!",
    "exEn": "Hello, everyone!"
  },
  {
    "rank": 14,
    "c": "中",
    "py": "zhōng",
    "en": "middle; China (abbr.)",
    "ex": "我在中国。",
    "exPy": "wǒ zài zhōng guó.",
    "exEn": "I'm in China."
  },
  {
    "rank": 15,
    "c": "来",
    "py": "lái",
    "en": "to come",
    "ex": "你快来！",
    "exPy": "nǐ kuài lái!",
    "exEn": "Come quick!"
  },
  {
    "rank": 16,
    "c": "上",
    "py": "shàng",
    "en": "on; above; to go up",
    "ex": "桌子上有一本书。",
    "exPy": "zhuō zi shàng yǒu yì běn shū.",
    "exEn": "There's a book on the table."
  },
  {
    "rank": 17,
    "c": "大",
    "py": "dà",
    "en": "big",
    "ex": "这个太大了。",
    "exPy": "zhè ge tài dà le.",
    "exEn": "This is too big."
  },
  {
    "rank": 18,
    "c": "为",
    "py": "wèi",
    "en": "for; because of",
    "ex": "我为你高兴。",
    "exPy": "wǒ wèi nǐ gāo xìng.",
    "exEn": "I'm happy for you."
  },
  {
    "rank": 19,
    "c": "和",
    "py": "hé",
    "en": "and; with",
    "ex": "我和你一起去。",
    "exPy": "wǒ hé nǐ yì qǐ qù.",
    "exEn": "I'll go with you."
  },
  {
    "rank": 20,
    "c": "国",
    "py": "guó",
    "en": "country",
    "ex": "你是哪国人？",
    "exPy": "nǐ shì nǎ guó rén?",
    "exEn": "Which country are you from?"
  },
  {
    "rank": 21,
    "c": "地",
    "py": "de",
    "en": "-ly (adverbial particle)",
    "ex": "他慢慢地走。",
    "exPy": "tā màn màn de zǒu.",
    "exEn": "He walked slowly."
  },
  {
    "rank": 22,
    "c": "到",
    "py": "dào",
    "en": "to arrive; to",
    "ex": "我到了。",
    "exPy": "wǒ dào le.",
    "exEn": "I've arrived."
  },
  {
    "rank": 23,
    "c": "以",
    "py": "yǐ",
    "en": "(in 以为: to think, mistakenly)",
    "ex": "我以为你走了。",
    "exPy": "wǒ yǐ wéi nǐ zǒu le.",
    "exEn": "I thought you'd left."
  },
  {
    "rank": 24,
    "c": "说",
    "py": "shuō",
    "en": "to say; to speak",
    "ex": "你说什么？",
    "exPy": "nǐ shuō shén me?",
    "exEn": "What did you say?"
  },
  {
    "rank": 25,
    "c": "时",
    "py": "shí",
    "en": "time; when (in 有时)",
    "ex": "我有时会迟到。",
    "exPy": "wǒ yǒu shí huì chí dào.",
    "exEn": "I'm sometimes late."
  },
  {
    "rank": 26,
    "c": "要",
    "py": "yào",
    "en": "to want; will",
    "ex": "我要一杯水。",
    "exPy": "wǒ yào yì bēi shuǐ.",
    "exEn": "I want a glass of water."
  },
  {
    "rank": 27,
    "c": "就",
    "py": "jiù",
    "en": "just; then (emphasis)",
    "ex": "我马上就到。",
    "exPy": "wǒ mǎ shàng jiù dào.",
    "exEn": "I'll be there right away."
  },
  {
    "rank": 28,
    "c": "出",
    "py": "chū",
    "en": "to go out; to exit",
    "ex": "我们出去吧。",
    "exPy": "wǒ men chū qù ba.",
    "exEn": "Let's go out."
  },
  {
    "rank": 29,
    "c": "会",
    "py": "huì",
    "en": "can; to know how to; will",
    "ex": "你会说中文吗？",
    "exPy": "nǐ huì shuō zhōng wén ma?",
    "exEn": "Can you speak Chinese?"
  },
  {
    "rank": 30,
    "c": "可",
    "py": "kě",
    "en": "can; may (in 可以)",
    "ex": "可以进来吗？",
    "exPy": "kě yǐ jìn lái ma?",
    "exEn": "May I come in?",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 可以 is written kě yǐ but said ké yǐ."
  },
  {
    "rank": 31,
    "c": "也",
    "py": "yě",
    "en": "also; too",
    "ex": "我也是。",
    "exPy": "wǒ yě shì.",
    "exEn": "Me too."
  },
  {
    "rank": 32,
    "c": "你",
    "py": "nǐ",
    "en": "you",
    "ex": "你好吗？",
    "exPy": "nǐ hǎo ma?",
    "exEn": "How are you?",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 你好 is written nǐ hǎo but said ní hǎo."
  },
  {
    "rank": 33,
    "c": "对",
    "py": "duì",
    "en": "correct; towards",
    "ex": "你说得对。",
    "exPy": "nǐ shuō de duì.",
    "exEn": "You're right."
  },
  {
    "rank": 34,
    "c": "生",
    "py": "shēng",
    "en": "life; to be born (in 生日)",
    "ex": "生日快乐！",
    "exPy": "shēng rì kuài lè!",
    "exEn": "Happy birthday!"
  },
  {
    "rank": 35,
    "c": "能",
    "py": "néng",
    "en": "can; to be able to",
    "ex": "我能帮你吗？",
    "exPy": "wǒ néng bāng nǐ ma?",
    "exEn": "Can I help you?"
  },
  {
    "rank": 36,
    "c": "而",
    "py": "ér",
    "en": "and also (in 而且)",
    "ex": "他又高又壮，而且很聪明。",
    "exPy": "tā yòu gāo yòu zhuàng, ér qiě hěn cōng míng.",
    "exEn": "He's tall and strong, and also very smart."
  },
  {
    "rank": 37,
    "c": "子",
    "py": "zi",
    "en": "(noun suffix)",
    "ex": "这是我儿子。",
    "exPy": "zhè shì wǒ ér zi.",
    "exEn": "This is my son."
  },
  {
    "rank": 38,
    "c": "那",
    "py": "nà",
    "en": "that",
    "ex": "那是谁？",
    "exPy": "nà shì shuí?",
    "exEn": "Who is that?"
  },
  {
    "rank": 39,
    "c": "得",
    "py": "dé",
    "en": "to get; to obtain",
    "ex": "我得到了好消息。",
    "exPy": "wǒ dé dào le hǎo xiāo xī.",
    "exEn": "I got good news."
  },
  {
    "rank": 40,
    "c": "于",
    "py": "yú",
    "en": "(formal: in, at; in 取决于)",
    "ex": "这取决于你。",
    "exPy": "zhè qǔ jué yú nǐ.",
    "exEn": "It depends on you."
  },
  {
    "rank": 41,
    "c": "着",
    "py": "zhe",
    "en": "(progressive aspect particle)",
    "ex": "我在等着你。",
    "exPy": "wǒ zài děng zhe nǐ.",
    "exEn": "I'm waiting for you."
  },
  {
    "rank": 42,
    "c": "下",
    "py": "xià",
    "en": "under; below; next",
    "ex": "下雨了。",
    "exPy": "xià yǔ le.",
    "exEn": "It's raining."
  },
  {
    "rank": 43,
    "c": "自",
    "py": "zì",
    "en": "self (in 自己)",
    "ex": "我自己来。",
    "exPy": "wǒ zì jǐ lái.",
    "exEn": "I'll do it myself."
  },
  {
    "rank": 44,
    "c": "之",
    "py": "zhī",
    "en": "(formal connector, in 总之)",
    "ex": "总之，我同意。",
    "exPy": "zǒng zhī, wǒ tóng yì.",
    "exEn": "In short, I agree."
  },
  {
    "rank": 45,
    "c": "年",
    "py": "nián",
    "en": "year",
    "ex": "明年见！",
    "exPy": "míng nián jiàn!",
    "exEn": "See you next year!"
  },
  {
    "rank": 46,
    "c": "过",
    "py": "guò",
    "en": "to pass; (experienced-action particle)",
    "ex": "我去过北京。",
    "exPy": "wǒ qù guò běi jīng.",
    "exEn": "I've been to Beijing."
  },
  {
    "rank": 47,
    "c": "发",
    "py": "fā",
    "en": "to send; to issue",
    "ex": "我发给你了。",
    "exPy": "wǒ fā gěi nǐ le.",
    "exEn": "I sent it to you."
  },
  {
    "rank": 48,
    "c": "后",
    "py": "hòu",
    "en": "after; behind",
    "ex": "放学后见。",
    "exPy": "fàng xué hòu jiàn.",
    "exEn": "See you after school."
  },
  {
    "rank": 49,
    "c": "作",
    "py": "zuò",
    "en": "to do; to make (in 工作)",
    "ex": "我在工作。",
    "exPy": "wǒ zài gōng zuò.",
    "exEn": "I'm working."
  },
  {
    "rank": 50,
    "c": "里",
    "py": "lǐ",
    "en": "inside; in",
    "ex": "我在家里。",
    "exPy": "wǒ zài jiā lǐ.",
    "exEn": "I'm at home (inside)."
  },
  {
    "rank": 51,
    "c": "用",
    "py": "yòng",
    "en": "to use",
    "ex": "你会用这个吗？",
    "exPy": "nǐ huì yòng zhè ge ma?",
    "exEn": "Do you know how to use this?"
  },
  {
    "rank": 52,
    "c": "道",
    "py": "dào",
    "en": "way; to say (in 知道)",
    "ex": "我知道了。",
    "exPy": "wǒ zhī dào le.",
    "exEn": "Got it."
  },
  {
    "rank": 53,
    "c": "行",
    "py": "xíng",
    "en": "OK; to walk; to be alright",
    "ex": "行，就这么办。",
    "exPy": "xíng, jiù zhè me bàn.",
    "exEn": "OK, let's do it that way."
  },
  {
    "rank": 54,
    "c": "所",
    "py": "suǒ",
    "en": "place (in 所以)",
    "ex": "所以我没去。",
    "exPy": "suǒ yǐ wǒ méi qù.",
    "exEn": "So I didn't go.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 所以 is written suǒ yǐ but said suó yǐ."
  },
  {
    "rank": 55,
    "c": "然",
    "py": "rán",
    "en": "so; like that (in 然后)",
    "ex": "然后呢？",
    "exPy": "rán hòu ne?",
    "exEn": "And then what?"
  },
  {
    "rank": 56,
    "c": "家",
    "py": "jiā",
    "en": "home; family",
    "ex": "我要回家了。",
    "exPy": "wǒ yào huí jiā le.",
    "exEn": "I'm heading home."
  },
  {
    "rank": 57,
    "c": "种",
    "py": "zhǒng",
    "en": "kind; type; to plant",
    "ex": "这种事很常见。",
    "exPy": "zhè zhǒng shì hěn cháng jiàn.",
    "exEn": "This kind of thing is common."
  },
  {
    "rank": 58,
    "c": "事",
    "py": "shì",
    "en": "matter; thing; affair",
    "ex": "没事儿。",
    "exPy": "méi shìr.",
    "exEn": "It's nothing; no worries."
  },
  {
    "rank": 59,
    "c": "成",
    "py": "chéng",
    "en": "to become; to succeed",
    "ex": "我们成功了！",
    "exPy": "wǒ men chéng gōng le!",
    "exEn": "We did it!"
  },
  {
    "rank": 60,
    "c": "方",
    "py": "fāng",
    "en": "square; place (in 地方)",
    "ex": "这个地方真漂亮。",
    "exPy": "zhè ge dì fāng zhēn piào liàng.",
    "exEn": "This place is really pretty."
  },
  {
    "rank": 61,
    "c": "多",
    "py": "duō",
    "en": "many; much",
    "ex": "你多大了？",
    "exPy": "nǐ duō dà le?",
    "exEn": "How old are you?"
  },
  {
    "rank": 62,
    "c": "经",
    "py": "jīng",
    "en": "to pass through (in 已经)",
    "ex": "我已经吃了。",
    "exPy": "wǒ yǐ jīng chī le.",
    "exEn": "I've already eaten."
  },
  {
    "rank": 63,
    "c": "么",
    "py": "me",
    "en": "(question suffix, in 什么/怎么)",
    "ex": "你在干什么？",
    "exPy": "nǐ zài gàn shén me?",
    "exEn": "What are you doing?"
  },
  {
    "rank": 64,
    "c": "去",
    "py": "qù",
    "en": "to go",
    "ex": "你要去哪儿？",
    "exPy": "nǐ yào qù nǎr?",
    "exEn": "Where are you going?"
  },
  {
    "rank": 65,
    "c": "法",
    "py": "fǎ",
    "en": "method (in 办法)",
    "ex": "有什么办法吗？",
    "exPy": "yǒu shén me bàn fǎ ma?",
    "exEn": "Is there any way to solve this?"
  },
  {
    "rank": 66,
    "c": "学",
    "py": "xué",
    "en": "to study; to learn",
    "ex": "我在学中文。",
    "exPy": "wǒ zài xué zhōng wén.",
    "exEn": "I'm learning Chinese."
  },
  {
    "rank": 67,
    "c": "如",
    "py": "rú",
    "en": "if; like (in 如果)",
    "ex": "如果你忙，就别来了。",
    "exPy": "rú guǒ nǐ máng, jiù bié lái le.",
    "exEn": "If you're busy, don't bother coming."
  },
  {
    "rank": 68,
    "c": "都",
    "py": "dōu",
    "en": "all; both",
    "ex": "我们都到了。",
    "exPy": "wǒ men dōu dào le.",
    "exEn": "We've all arrived."
  },
  {
    "rank": 69,
    "c": "同",
    "py": "tóng",
    "en": "same; together (in 同学)",
    "ex": "我们是同学。",
    "exPy": "wǒ men shì tóng xué.",
    "exEn": "We're classmates."
  },
  {
    "rank": 70,
    "c": "现",
    "py": "xiàn",
    "en": "now (in 现在)",
    "ex": "你现在在哪儿？",
    "exPy": "nǐ xiàn zài zài nǎr?",
    "exEn": "Where are you right now?"
  },
  {
    "rank": 71,
    "c": "当",
    "py": "dāng",
    "en": "of course (in 当然); to serve as",
    "ex": "那当然！",
    "exPy": "nà dāng rán!",
    "exEn": "Of course!"
  },
  {
    "rank": 72,
    "c": "没",
    "py": "méi",
    "en": "not (have); did not",
    "ex": "我没听懂。",
    "exPy": "wǒ méi tīng dǒng.",
    "exEn": "I didn't understand."
  },
  {
    "rank": 73,
    "c": "动",
    "py": "dòng",
    "en": "to move; to act",
    "ex": "别动！",
    "exPy": "bié dòng!",
    "exEn": "Don't move!"
  },
  {
    "rank": 74,
    "c": "面",
    "py": "miàn",
    "en": "face; side; noodles",
    "ex": "我们见面聊吧。",
    "exPy": "wǒ men jiàn miàn liáo ba.",
    "exEn": "Let's meet up and talk."
  },
  {
    "rank": 75,
    "c": "起",
    "py": "qǐ",
    "en": "to rise; up (in 一起)",
    "ex": "我们一起去吧。",
    "exPy": "wǒ men yì qǐ qù ba.",
    "exEn": "Let's go together."
  },
  {
    "rank": 76,
    "c": "看",
    "py": "kàn",
    "en": "to look; to watch; to read",
    "ex": "你在看什么？",
    "exPy": "nǐ zài kàn shén me?",
    "exEn": "What are you watching?"
  },
  {
    "rank": 77,
    "c": "定",
    "py": "dìng",
    "en": "surely (in 一定); to decide",
    "ex": "我一定会去。",
    "exPy": "wǒ yí dìng huì qù.",
    "exEn": "I will definitely go."
  },
  {
    "rank": 78,
    "c": "天",
    "py": "tiān",
    "en": "day; sky",
    "ex": "今天天气真好。",
    "exPy": "jīn tiān tiān qì zhēn hǎo.",
    "exEn": "The weather's really nice today."
  },
  {
    "rank": 79,
    "c": "分",
    "py": "fēn",
    "en": "to divide; minute; point",
    "ex": "还有五分钟。",
    "exPy": "hái yǒu wǔ fēn zhōng.",
    "exEn": "There are five more minutes."
  },
  {
    "rank": 80,
    "c": "还",
    "py": "hái",
    "en": "still; also; even more",
    "ex": "你还好吗？",
    "exPy": "nǐ hái hǎo ma?",
    "exEn": "Are you okay?"
  },
  {
    "rank": 81,
    "c": "进",
    "py": "jìn",
    "en": "to enter",
    "ex": "请进！",
    "exPy": "qǐng jìn!",
    "exEn": "Please come in!"
  },
  {
    "rank": 82,
    "c": "好",
    "py": "hǎo",
    "en": "good; well; OK",
    "ex": "好的，没问题！",
    "exPy": "hǎo de, méi wèn tí!",
    "exEn": "OK, no problem!"
  },
  {
    "rank": 83,
    "c": "小",
    "py": "xiǎo",
    "en": "small; little",
    "ex": "这只是小事。",
    "exPy": "zhè zhǐ shì xiǎo shì.",
    "exEn": "It's just a small thing."
  },
  {
    "rank": 84,
    "c": "部",
    "py": "bù",
    "en": "part; unit (measure word for films)",
    "ex": "这部电影很好看。",
    "exPy": "zhè bù diàn yǐng hěn hǎo kàn.",
    "exEn": "This movie is really good."
  },
  {
    "rank": 85,
    "c": "其",
    "py": "qí",
    "en": "actually (in 其实)",
    "ex": "其实我不太喜欢。",
    "exPy": "qí shí wǒ bú tài xǐ huān.",
    "exEn": "Actually, I don't really like it."
  },
  {
    "rank": 86,
    "c": "些",
    "py": "xiē",
    "en": "some; a few",
    "ex": "你要不要吃一些？",
    "exPy": "nǐ yào bú yào chī yì xiē?",
    "exEn": "Do you want to eat some?"
  },
  {
    "rank": 87,
    "c": "主",
    "py": "zhǔ",
    "en": "main (in 主意)",
    "ex": "这是个好主意！",
    "exPy": "zhè shì gè hǎo zhǔ yì!",
    "exEn": "That's a good idea!"
  },
  {
    "rank": 88,
    "c": "样",
    "py": "yàng",
    "en": "kind; way (in 这样/怎么样)",
    "ex": "你觉得怎么样？",
    "exPy": "nǐ jué de zěn me yàng?",
    "exEn": "What do you think?"
  },
  {
    "rank": 89,
    "c": "理",
    "py": "lǐ",
    "en": "reason; sense (in 道理)",
    "ex": "你说得有道理。",
    "exPy": "nǐ shuō de yǒu dào lǐ.",
    "exEn": "What you said makes sense."
  },
  {
    "rank": 90,
    "c": "心",
    "py": "xīn",
    "en": "heart; mind",
    "ex": "别担心。",
    "exPy": "bié dān xīn.",
    "exEn": "Don't worry."
  },
  {
    "rank": 91,
    "c": "她",
    "py": "tā",
    "en": "she; her",
    "ex": "她是谁？",
    "exPy": "tā shì shuí?",
    "exEn": "Who is she?"
  },
  {
    "rank": 92,
    "c": "本",
    "py": "běn",
    "en": "originally (in 本来)",
    "ex": "我本来想去。",
    "exPy": "wǒ běn lái xiǎng qù.",
    "exEn": "I originally wanted to go."
  },
  {
    "rank": 93,
    "c": "前",
    "py": "qián",
    "en": "front; before; ago",
    "ex": "你以前来过吗？",
    "exPy": "nǐ yǐ qián lái guò ma?",
    "exEn": "Have you been here before?"
  },
  {
    "rank": 94,
    "c": "开",
    "py": "kāi",
    "en": "to open; to start; to drive",
    "ex": "快开门！",
    "exPy": "kuài kāi mén!",
    "exEn": "Open the door, quick!"
  },
  {
    "rank": 95,
    "c": "但",
    "py": "dàn",
    "en": "but; however",
    "ex": "我很累，但是很开心。",
    "exPy": "wǒ hěn lèi, dàn shì hěn kāi xīn.",
    "exEn": "I'm tired, but happy."
  },
  {
    "rank": 96,
    "c": "因",
    "py": "yīn",
    "en": "because (of) (in 因为)",
    "ex": "因为下雨，我没去。",
    "exPy": "yīn wèi xià yǔ, wǒ méi qù.",
    "exEn": "I didn't go because it was raining."
  },
  {
    "rank": 97,
    "c": "只",
    "py": "zhǐ",
    "en": "only; just",
    "ex": "我只是问问。",
    "exPy": "wǒ zhǐ shì wèn wèn.",
    "exEn": "I'm just asking."
  },
  {
    "rank": 98,
    "c": "从",
    "py": "cóng",
    "en": "from",
    "ex": "你从哪儿来？",
    "exPy": "nǐ cóng nǎr lái?",
    "exEn": "Where are you from?"
  },
  {
    "rank": 99,
    "c": "想",
    "py": "xiǎng",
    "en": "to think; to want; to miss",
    "ex": "我想你了。",
    "exPy": "wǒ xiǎng nǐ le.",
    "exEn": "I miss you.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 想你 is written xiǎng nǐ but said xiáng nǐ."
  },
  {
    "rank": 100,
    "c": "实",
    "py": "shí",
    "en": "real; true (in 其实/说实话)",
    "ex": "说实话，我不知道。",
    "exPy": "shuō shí huà, wǒ bù zhī dào.",
    "exEn": "To be honest, I don't know."
  },
  {
    "rank": 101,
    "c": "日",
    "py": "rì",
    "en": "sun; day",
    "ex": "今天是几月几日？",
    "exPy": "jīn tiān shì jǐ yuè jǐ rì?",
    "exEn": "What's today's date?"
  },
  {
    "rank": 102,
    "c": "军",
    "py": "jūn",
    "en": "army; military",
    "ex": "他当过军人。",
    "exPy": "tā dāng guò jūn rén.",
    "exEn": "He used to be a soldier."
  },
  {
    "rank": 103,
    "c": "者",
    "py": "zhě",
    "en": "(suffix: one who; or)",
    "ex": "你去或者我去，都行。",
    "exPy": "nǐ qù huò zhě wǒ qù, dōu xíng.",
    "exEn": "Either you go or I go, both are fine.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 者我 is written zhě wǒ but said zhé wǒ."
  },
  {
    "rank": 104,
    "c": "意",
    "py": "yì",
    "en": "meaning; idea (in 意思)",
    "ex": "这是什么意思？",
    "exPy": "zhè shì shén me yì si?",
    "exEn": "What does this mean?"
  },
  {
    "rank": 105,
    "c": "无",
    "py": "wú",
    "en": "without; not (formal, in 无所谓)",
    "ex": "无所谓，随便你。",
    "exPy": "wú suǒ wèi, suí biàn nǐ.",
    "exEn": "Whatever, up to you."
  },
  {
    "rank": 106,
    "c": "力",
    "py": "lì",
    "en": "strength; effort (in 努力)",
    "ex": "你要努力！",
    "exPy": "nǐ yào nǔ lì!",
    "exEn": "You need to work hard!"
  },
  {
    "rank": 107,
    "c": "它",
    "py": "tā",
    "en": "it",
    "ex": "它是我的猫。",
    "exPy": "tā shì wǒ de māo.",
    "exEn": "It's my cat."
  },
  {
    "rank": 108,
    "c": "与",
    "py": "yǔ",
    "en": "and; with (formal)",
    "ex": "这与我无关。",
    "exPy": "zhè yǔ wǒ wú guān.",
    "exEn": "This has nothing to do with me.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 与我 is written yǔ wǒ but said yú wǒ."
  },
  {
    "rank": 109,
    "c": "长",
    "py": "zhǎng",
    "en": "to grow; long",
    "ex": "你长高了！",
    "exPy": "nǐ zhǎng gāo le!",
    "exEn": "You've grown taller!"
  },
  {
    "rank": 110,
    "c": "把",
    "py": "bǎ",
    "en": "(object-marker); to hold",
    "ex": "把门关上。",
    "exPy": "bǎ mén guān shàng.",
    "exEn": "Close the door."
  },
  {
    "rank": 111,
    "c": "机",
    "py": "jī",
    "en": "machine (in 手机)",
    "ex": "我手机没电了。",
    "exPy": "wǒ shǒu jī méi diàn le.",
    "exEn": "My phone's out of battery."
  },
  {
    "rank": 112,
    "c": "十",
    "py": "shí",
    "en": "ten",
    "ex": "我要十个饺子。",
    "exPy": "wǒ yào shí gè jiǎo zi.",
    "exEn": "I'll have ten dumplings."
  },
  {
    "rank": 113,
    "c": "民",
    "py": "mín",
    "en": "people; citizens (in 移民)",
    "ex": "移民很不容易。",
    "exPy": "yí mín hěn bù róng yì.",
    "exEn": "Immigrating isn't easy."
  },
  {
    "rank": 114,
    "c": "第",
    "py": "dì",
    "en": "(ordinal prefix)",
    "ex": "这是我第一次来。",
    "exPy": "zhè shì wǒ dì yī cì lái.",
    "exEn": "This is my first time here."
  },
  {
    "rank": 115,
    "c": "公",
    "py": "gōng",
    "en": "public (in 公司)",
    "ex": "我在公司加班。",
    "exPy": "wǒ zài gōng sī jiā bān.",
    "exEn": "I'm working overtime at the office."
  },
  {
    "rank": 116,
    "c": "此",
    "py": "cǐ",
    "en": "this (formal, in 因此)",
    "ex": "因此，我们决定取消。",
    "exPy": "yīn cǐ, wǒ men jué dìng qǔ xiāo.",
    "exEn": "So, we decided to cancel."
  },
  {
    "rank": 117,
    "c": "已",
    "py": "yǐ",
    "en": "already (in 已经)",
    "ex": "我已经到了。",
    "exPy": "wǒ yǐ jīng dào le.",
    "exEn": "I've already arrived."
  },
  {
    "rank": 118,
    "c": "工",
    "py": "gōng",
    "en": "work; labor",
    "ex": "这个工作很有意思。",
    "exPy": "zhè ge gōng zuò hěn yǒu yì si.",
    "exEn": "This job is interesting."
  },
  {
    "rank": 119,
    "c": "使",
    "py": "shǐ",
    "en": "to make; even if (in 即使)",
    "ex": "即使很累，我也要去。",
    "exPy": "jí shǐ hěn lèi, wǒ yě yào qù.",
    "exEn": "Even if I'm tired, I'll still go.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 使很 is written shǐ hěn but said shí hěn."
  },
  {
    "rank": 120,
    "c": "情",
    "py": "qíng",
    "en": "feeling; mood (in 心情)",
    "ex": "你今天心情怎么样？",
    "exPy": "nǐ jīn tiān xīn qíng zěn me yàng?",
    "exEn": "How are you feeling today?"
  },
  {
    "rank": 121,
    "c": "明",
    "py": "míng",
    "en": "clear; to understand (in 明白)",
    "ex": "我明白了。",
    "exPy": "wǒ míng bái le.",
    "exEn": "I understand now."
  },
  {
    "rank": 122,
    "c": "性",
    "py": "xìng",
    "en": "nature; character (in 性格)",
    "ex": "他性格很好。",
    "exPy": "tā xìng gé hěn hǎo.",
    "exEn": "He has a good personality."
  },
  {
    "rank": 123,
    "c": "知",
    "py": "zhī",
    "en": "to know (in 知道)",
    "ex": "你知道吗？",
    "exPy": "nǐ zhī dào ma?",
    "exEn": "Do you know?"
  },
  {
    "rank": 124,
    "c": "全",
    "py": "quán",
    "en": "whole; entire",
    "ex": "我们全都同意。",
    "exPy": "wǒ men quán dōu tóng yì.",
    "exEn": "We all agree."
  },
  {
    "rank": 125,
    "c": "三",
    "py": "sān",
    "en": "three",
    "ex": "我们三个人一起去。",
    "exPy": "wǒ men sān gè rén yì qǐ qù.",
    "exEn": "The three of us will go together."
  },
  {
    "rank": 126,
    "c": "又",
    "py": "yòu",
    "en": "again; also",
    "ex": "你又迟到了！",
    "exPy": "nǐ yòu chí dào le!",
    "exEn": "You're late again!"
  },
  {
    "rank": 127,
    "c": "关",
    "py": "guān",
    "en": "to close; related (in 没关系)",
    "ex": "没关系。",
    "exPy": "méi guān xì.",
    "exEn": "No worries; it's okay."
  },
  {
    "rank": 128,
    "c": "点",
    "py": "diǎn",
    "en": "o'clock; a bit; dot",
    "ex": "几点了？",
    "exPy": "jǐ diǎn le?",
    "exEn": "What time is it?"
  },
  {
    "rank": 129,
    "c": "正",
    "py": "zhèng",
    "en": "exactly; right now (in 正在)",
    "ex": "我正在吃饭。",
    "exPy": "wǒ zhèng zài chī fàn.",
    "exEn": "I'm eating right now."
  },
  {
    "rank": 130,
    "c": "业",
    "py": "yè",
    "en": "profession (in 作业/毕业)",
    "ex": "你做完作业了吗？",
    "exPy": "nǐ zuò wán zuò yè le ma?",
    "exEn": "Have you finished your homework?"
  },
  {
    "rank": 131,
    "c": "外",
    "py": "wài",
    "en": "outside; foreign",
    "ex": "外面在下雨。",
    "exPy": "wài miàn zài xià yǔ.",
    "exEn": "It's raining outside."
  },
  {
    "rank": 132,
    "c": "将",
    "py": "jiāng",
    "en": "will (in 将来)",
    "ex": "我将来想当医生。",
    "exPy": "wǒ jiāng lái xiǎng dāng yī shēng.",
    "exEn": "In the future, I want to be a doctor."
  },
  {
    "rank": 133,
    "c": "两",
    "py": "liǎng",
    "en": "two (measure use)",
    "ex": "我要两杯奶茶。",
    "exPy": "wǒ yào liǎng bēi nǎi chá.",
    "exEn": "I want two milk teas."
  },
  {
    "rank": 134,
    "c": "高",
    "py": "gāo",
    "en": "tall; high",
    "ex": "他很高。",
    "exPy": "tā hěn gāo.",
    "exEn": "He's tall."
  },
  {
    "rank": 135,
    "c": "间",
    "py": "jiān",
    "en": "room (in 房间)",
    "ex": "我们的房间在哪儿？",
    "exPy": "wǒ men de fáng jiān zài nǎr?",
    "exEn": "Where's our room?"
  },
  {
    "rank": 136,
    "c": "由",
    "py": "yóu",
    "en": "due to (in 由于)",
    "ex": "由于堵车，我迟到了。",
    "exPy": "yóu yú dǔ chē, wǒ chí dào le.",
    "exEn": "I was late due to traffic."
  },
  {
    "rank": 137,
    "c": "问",
    "py": "wèn",
    "en": "to ask",
    "ex": "我可以问你一个问题吗？",
    "exPy": "wǒ kě yǐ wèn nǐ yí gè wèn tí ma?",
    "exEn": "Can I ask you a question?"
  },
  {
    "rank": 138,
    "c": "很",
    "py": "hěn",
    "en": "very",
    "ex": "今天很热。",
    "exPy": "jīn tiān hěn rè.",
    "exEn": "It's very hot today."
  },
  {
    "rank": 139,
    "c": "最",
    "py": "zuì",
    "en": "most; -est",
    "ex": "这是我最喜欢的歌。",
    "exPy": "zhè shì wǒ zuì xǐ huān de gē.",
    "exEn": "This is my favorite song."
  },
  {
    "rank": 140,
    "c": "重",
    "py": "zhòng",
    "en": "heavy; important (in 重要)",
    "ex": "这件事很重要。",
    "exPy": "zhè jiàn shì hěn zhòng yào.",
    "exEn": "This matter is very important."
  }
];
