// Auto-generated by tools/gen_colloquial_data.py — do not edit by hand.
// Character + pinyin from Jun Da's frequency list; examples hand-authored,
// example pinyin produced with pypinyin (tone marks).
window.COLLOQUIAL_DATA = [
  {
    "rank": 1,
    "c": "的",
    "py": "de",
    "en": "of; 's (possessive particle)",
    "ex": "这是我的手机。",
    "exPy": "zhè shì wǒ de shǒu jī.",
    "exEn": "This is my phone.",
    "parts": "白 white + 勺 ladle",
    "mnem": "A <b>white</b> (白) <b>ladle</b> (勺) — whose is it? Mark the owner with 的: 我的 = mine.",
    "lesson": {
      "uses": [
        {
          "g": "possession: X 的 Y = “X's Y”",
          "h": "我的",
          "hPy": "wǒ de",
          "ex": "这是妈妈的钥匙。",
          "exPy": "zhè shì mā ma de yào shi.",
          "exEn": "These are mom's keys."
        },
        {
          "g": "glues any description to a noun: description + 的 + noun",
          "h": "红色的",
          "hPy": "hóng sè de",
          "ex": "我喜欢红色的车。",
          "exPy": "wǒ xǐ huān hóng sè de chē.",
          "exEn": "I like red cars."
        },
        {
          "g": "drop the noun and 的 means “the … one / … stuff”",
          "h": "吃的",
          "hPy": "chī de",
          "ex": "有什么好吃的？",
          "exPy": "yǒu shén me hǎo chī de?",
          "exEn": "Anything tasty around?"
        },
        {
          "g": "wraps up how/when/where something happened, for emphasis",
          "h": "是……的",
          "hPy": "shì … de",
          "ex": "我是坐飞机来的。",
          "exPy": "wǒ shì zuò fēi jī lái de.",
          "exEn": "I came by plane (that's how)."
        },
        {
          "g": "Watch the readings: dì in 目的 (mùdì, goal), dí in 的确 (díquè, indeed)."
        }
      ],
      "intro": "The single most common character in Chinese — a little glue word with three main jobs."
    }
  },
  {
    "rank": 2,
    "c": "一",
    "py": "yī",
    "en": "one",
    "ex": "我要一杯咖啡。",
    "exPy": "wǒ yào yì bēi kā fēi.",
    "exEn": "I want one coffee.",
    "tone": "Tone change: 一 is yī alone or in numbers/dates, yí before a 4th tone, yì before 1st/2nd/3rd tones — here 一杯 is yì bēi.",
    "parts": "one stroke",
    "mnem": "<b>One</b> single stroke — the simplest character there is.",
    "lesson": {
      "uses": [
        {
          "g": "plain counting: 一 + measure word + noun",
          "h": "一个",
          "hPy": "yí gè",
          "ex": "我买了一个包子。",
          "exPy": "wǒ mǎi le yí gè bāo zi.",
          "exEn": "I bought a steamed bun."
        },
        {
          "g": "verb + 一下 softens it: “real quick, a bit”",
          "h": "一下",
          "hPy": "yí xià",
          "ex": "你等一下！",
          "exPy": "nǐ děng yí xià!",
          "exEn": "Wait a sec!"
        },
        {
          "g": "“a little”",
          "h": "一点儿",
          "hPy": "yì diǎnr",
          "ex": "我会说一点儿中文。",
          "exPy": "wǒ huì shuō yì diǎnr zhōng wén.",
          "exEn": "I speak a little Chinese."
        },
        {
          "g": "“together”",
          "h": "一起",
          "hPy": "yì qǐ",
          "ex": "明天一起吃饭吧。",
          "exPy": "míng tiān yì qǐ chī fàn ba.",
          "exEn": "Let's eat together tomorrow."
        }
      ],
      "intro": "Not just the number one — 一 powers a bunch of everyday patterns."
    }
  },
  {
    "rank": 3,
    "c": "是",
    "py": "shì",
    "en": "to be; yes",
    "ex": "我是学生。",
    "exPy": "wǒ shì xué shēng.",
    "exEn": "I am a student.",
    "parts": "日 sun over a straight base",
    "mnem": "Under the <b>sun</b> (日) everything stands straight and true — “it <b>is</b> so.”",
    "lesson": {
      "uses": [
        {
          "g": "identifying things: “A is B”",
          "h": "A 是 B",
          "hPy": "A shì B",
          "ex": "他是我哥哥。",
          "exPy": "tā shì wǒ gē ge.",
          "exEn": "He's my older brother."
        },
        {
          "g": "agreeing: “yeah, right?”",
          "h": "是啊",
          "hPy": "shì a",
          "ex": "是啊，太贵了！",
          "exPy": "shì a, tài guì le!",
          "exEn": "Yeah, way too expensive!"
        },
        {
          "g": "emphasizes when/how/where something happened",
          "h": "是……的",
          "hPy": "shì … de",
          "ex": "这是我自己做的。",
          "exPy": "zhè shì wǒ zì jǐ zuò de.",
          "exEn": "I made this myself."
        }
      ]
    }
  },
  {
    "rank": 4,
    "c": "不",
    "py": "bù",
    "en": "not; no",
    "ex": "我不知道。",
    "exPy": "wǒ bù zhī dào.",
    "exEn": "I don't know.",
    "tone": "Tone change: 不 becomes bú before a 4th tone, otherwise bù — here 不知 is bù zhī.",
    "parts": "pictograph: a root blocked by the ground",
    "mnem": "A seed's root hits solid rock and can't sprout — <b>no</b>, <b>not</b> happening.",
    "lesson": {
      "uses": [
        {
          "g": "straight negation, right before a verb or adjective",
          "ex": "我今天不去。",
          "exPy": "wǒ jīn tiān bú qù.",
          "exEn": "I'm not going today."
        },
        {
          "g": "verb + 不 + verb makes a casual yes/no question",
          "h": "去不去",
          "hPy": "qù bú qù",
          "ex": "你去不去？",
          "exPy": "nǐ qù bú qù?",
          "exEn": "Are you going or not?"
        },
        {
          "g": "“no need” — the polite way to decline",
          "h": "不用",
          "hPy": "bú yòng",
          "ex": "不用了，谢谢！",
          "exPy": "bú yòng le, xiè xiè!",
          "exEn": "No need, thanks!"
        }
      ]
    }
  },
  {
    "rank": 5,
    "c": "了",
    "py": "le",
    "en": "(completed action / change particle)",
    "ex": "我吃了。",
    "exPy": "wǒ chī le.",
    "exEn": "I've eaten.",
    "parts": "子 child without arms",
    "mnem": "A <b>child</b> (子) swaddled with its arms wrapped in — nothing left to do: done, finished, 了.",
    "lesson": {
      "uses": [
        {
          "g": "right after the verb: the action happened, it's done",
          "ex": "我买了三本书。",
          "exPy": "wǒ mǎi le sān běn shū.",
          "exEn": "I bought three books."
        },
        {
          "g": "at the end of the sentence: new situation — something changed",
          "ex": "下雨了！",
          "exPy": "xià yǔ le!",
          "exEn": "It's raining (now)!"
        },
        {
          "g": "“too / so …!” — exclamation frame",
          "h": "太……了",
          "hPy": "tài … le",
          "ex": "太好了！",
          "exPy": "tài hǎo le!",
          "exEn": "Awesome!"
        },
        {
          "g": "“stop …ing”",
          "h": "别……了",
          "hPy": "bié … le",
          "ex": "别哭了。",
          "exPy": "bié kū le.",
          "exEn": "Stop crying."
        }
      ],
      "intro": "The famous 了 — two core jobs cover most of what you'll meet."
    }
  },
  {
    "rank": 6,
    "c": "在",
    "py": "zài",
    "en": "at; in; -ing (progressive)",
    "ex": "我在家。",
    "exPy": "wǒ zài jiā.",
    "exEn": "I'm at home.",
    "parts": "才 sprout + 土 earth",
    "mnem": "A sprout (才) rooted in the <b>earth</b> (土) — it exists somewhere: <b>at</b>, <b>in</b>.",
    "lesson": {
      "uses": [
        {
          "g": "full verb: to be at / in",
          "ex": "他在办公室。",
          "exPy": "tā zài bàn gōng shì.",
          "exEn": "He's in the office."
        },
        {
          "g": "before a place: “in/at …” + action",
          "ex": "我在北京工作。",
          "exPy": "wǒ zài běi jīng gōng zuò.",
          "exEn": "I work in Beijing."
        },
        {
          "g": "happening right now: “-ing”",
          "h": "在 + verb",
          "hPy": "zài + verb",
          "ex": "我在做饭。",
          "exPy": "wǒ zài zuò fàn.",
          "exEn": "I'm cooking."
        }
      ]
    }
  },
  {
    "rank": 7,
    "c": "人",
    "py": "rén",
    "en": "person; people",
    "ex": "他是好人。",
    "exPy": "tā shì hǎo rén.",
    "exEn": "He's a good person.",
    "parts": "pictograph: two legs walking",
    "mnem": "Two legs mid-stride — a <b>person</b> walking."
  },
  {
    "rank": 8,
    "c": "有",
    "py": "yǒu",
    "en": "to have; there is",
    "ex": "你有时间吗？",
    "exPy": "nǐ yǒu shí jiān ma?",
    "exEn": "Do you have time?",
    "parts": "𠂇 hand + 月 meat",
    "mnem": "A <b>hand</b> (𠂇) holding <b>meat</b> (月) — you <b>have</b> something."
  },
  {
    "rank": 9,
    "c": "我",
    "py": "wǒ",
    "en": "I; me",
    "ex": "我很好。",
    "exPy": "wǒ hěn hǎo.",
    "exEn": "I'm doing well.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 我很 is written wǒ hěn but said wó hěn.",
    "parts": "contains 戈 dagger-axe",
    "mnem": "<b>I</b> grip my <b>spear</b> (戈) and plant my feet — “me first, this is mine.”"
  },
  {
    "rank": 10,
    "c": "他",
    "py": "tā",
    "en": "he; him",
    "ex": "他在哪儿？",
    "exPy": "tā zài nǎr?",
    "exEn": "Where is he?",
    "parts": "亻 person + 也 also",
    "mnem": "That <b>person</b> (亻) over there is <b>also</b> (也) one of us — <b>he</b>."
  },
  {
    "rank": 11,
    "c": "这",
    "py": "zhè",
    "en": "this",
    "ex": "这个多少钱？",
    "exPy": "zhè ge duō shǎo qián?",
    "exEn": "How much is this?",
    "parts": "辶 walk + 文 writing",
    "mnem": "<b>Walk</b> (辶) over to the <b>writing</b> (文) and point right at it — <b>this</b> one."
  },
  {
    "rank": 12,
    "c": "个",
    "py": "gè",
    "en": "(general measure word)",
    "ex": "给我一个。",
    "exPy": "gěi wǒ yí gè.",
    "exEn": "Give me one.",
    "parts": "人 person + 丨 stick",
    "mnem": "A person holding one bamboo <b>stick</b> (丨) — one generic <b>item</b>: the all-purpose measure word.",
    "lesson": {
      "uses": [
        {
          "g": "the default measure word: number + 个 + noun",
          "ex": "我们班有二十个学生。",
          "exPy": "wǒ men bān yǒu èr shí gè xué shēng.",
          "exEn": "There are twenty students in our class."
        },
        {
          "g": "not sure which measure word fits? 个 is usually a safe fallback",
          "ex": "我有一个问题。",
          "exPy": "wǒ yǒu yí gè wèn tí.",
          "exEn": "I have a question."
        },
        {
          "g": "“this one / that one” — also the classic um-uh filler while you think",
          "h": "这个 / 那个",
          "hPy": "zhè ge / nà ge",
          "ex": "我要这个，不要那个。",
          "exPy": "wǒ yào zhè ge, bú yào nà ge.",
          "exEn": "I want this one, not that one."
        }
      ]
    }
  },
  {
    "rank": 13,
    "c": "们",
    "py": "men",
    "en": "(plural marker for pronouns/people)",
    "ex": "你们好！",
    "exPy": "nǐ men hǎo!",
    "exEn": "Hello, everyone!",
    "parts": "亻 person + 门 door (≈ <b>mén</b>, sound)",
    "mnem": "A crowd of <b>people</b> (亻) at the <b>door</b> (门) — the plural marker: 我们, 你们."
  },
  {
    "rank": 14,
    "c": "中",
    "py": "zhōng",
    "en": "middle; China (abbr.)",
    "ex": "我在中国。",
    "exPy": "wǒ zài zhōng guó.",
    "exEn": "I'm in China.",
    "parts": "口 box + 丨 line through the center",
    "mnem": "An arrow through the dead <b>center</b> of the target — <b>middle</b>."
  },
  {
    "rank": 15,
    "c": "来",
    "py": "lái",
    "en": "to come",
    "ex": "你快来！",
    "exPy": "nǐ kuài lái!",
    "exEn": "Come quick!",
    "parts": "pictograph: a wheat plant",
    "mnem": "Ripe wheat means guests <b>come</b> for the harvest — 来!"
  },
  {
    "rank": 16,
    "c": "上",
    "py": "shàng",
    "en": "on; above; to go up",
    "ex": "桌子上有一本书。",
    "exPy": "zhuō zi shàng yǒu yì běn shū.",
    "exEn": "There's a book on the table.",
    "parts": "a mark above the base line",
    "mnem": "A flag planted <b>above</b> the ground line — <b>up</b>, on top.",
    "lesson": {
      "uses": [
        {
          "g": "to go to (work, class) — 上 as “attend”",
          "h": "上班 / 上课",
          "hPy": "shàng bān / shàng kè",
          "ex": "我八点上班。",
          "exPy": "wǒ bā diǎn shàng bān.",
          "exEn": "I start work at eight."
        },
        {
          "g": "to get on / go online — 上 as “get onto”",
          "h": "上车 / 上网",
          "hPy": "shàng chē / shàng wǎng",
          "ex": "快上车！",
          "exPy": "kuài shàng chē!",
          "exEn": "Get in the car, quick!"
        },
        {
          "g": "“last” with time words",
          "h": "上个",
          "hPy": "shàng gè",
          "ex": "上个星期我很忙。",
          "exPy": "shàng gè xīng qī wǒ hěn máng.",
          "exEn": "I was really busy last week."
        }
      ]
    }
  },
  {
    "rank": 17,
    "c": "大",
    "py": "dà",
    "en": "big",
    "ex": "这个太大了。",
    "exPy": "zhè ge tài dà le.",
    "exEn": "This is too big.",
    "parts": "人 person with arms stretched wide",
    "mnem": "A person stretching their arms as wide as they can — “it was THIS <b>big</b>!”"
  },
  {
    "rank": 18,
    "c": "为",
    "py": "wèi",
    "en": "for; because of",
    "ex": "我为你高兴。",
    "exPy": "wǒ wèi nǐ gāo xìng.",
    "exEn": "I'm happy for you.",
    "parts": "from 爲: a hand leading an elephant",
    "mnem": "Originally a hand leading an elephant to work — effort <b>for</b> a purpose: 为你 for you.",
    "lesson": {
      "uses": [
        {
          "g": "“for” someone — for their sake",
          "h": "为你",
          "hPy": "wèi nǐ",
          "ex": "我为你骄傲！",
          "exPy": "wǒ wèi nǐ jiāo ào!",
          "exEn": "I'm proud of you!"
        },
        {
          "g": "“why” — literally “for what”",
          "h": "为什么",
          "hPy": "wèi shén me",
          "ex": "你为什么不吃？",
          "exPy": "nǐ wèi shén me bù chī?",
          "exEn": "Why aren't you eating?"
        },
        {
          "g": "“in order to” — states the purpose up front",
          "h": "为了",
          "hPy": "wèi le",
          "ex": "为了健康，我每天跑步。",
          "exPy": "wèi le jiàn kāng, wǒ měi tiān pǎo bù.",
          "exEn": "I run every day for my health."
        },
        {
          "g": "read wéi (2nd tone) in 认为 “to think” and 成为 “to become”",
          "h": "认为",
          "hPy": "rèn wéi",
          "ex": "我认为你是对的。",
          "exPy": "wǒ rèn wéi nǐ shì duì de.",
          "exEn": "I think you're right."
        }
      ]
    }
  },
  {
    "rank": 19,
    "c": "和",
    "py": "hé",
    "en": "and; with",
    "ex": "我和你一起去。",
    "exPy": "wǒ hé nǐ yì qǐ qù.",
    "exEn": "I'll go with you.",
    "parts": "禾 grain + 口 mouth",
    "mnem": "<b>Grain</b> (禾) in every <b>mouth</b> (口) — harmony: this <b>and</b> that, shared together."
  },
  {
    "rank": 20,
    "c": "国",
    "py": "guó",
    "en": "country",
    "ex": "你是哪国人？",
    "exPy": "nǐ shì nǎ guó rén?",
    "exEn": "Which country are you from?",
    "parts": "囗 border + 玉 jade",
    "mnem": "<b>Jade</b> (玉) treasure locked inside secure <b>borders</b> (囗) — a <b>country</b>."
  },
  {
    "rank": 21,
    "c": "地",
    "py": "de",
    "en": "-ly (adverbial particle)",
    "ex": "他慢慢地走。",
    "exPy": "tā màn màn de zǒu.",
    "exEn": "He walked slowly.",
    "parts": "土 earth + 也",
    "mnem": "<b>Earth</b> (土) is the base of everything — the ground; as a particle it grounds adverbs: 慢慢地 slowly.",
    "lesson": {
      "uses": [
        {
          "g": "de: adjective + 地 + verb turns it into an adverb (“-ly”)",
          "ex": "她开心地笑了。",
          "exPy": "tā kāi xīn de xiào le.",
          "exEn": "She smiled happily."
        },
        {
          "g": "dì: the ground, the earth",
          "ex": "地上都是水。",
          "exPy": "dì shàng dōu shì shuǐ.",
          "exEn": "There's water all over the floor."
        },
        {
          "g": "dì also starts place words: 地图 map, 地铁 metro",
          "ex": "我们坐地铁去吧。",
          "exPy": "wǒ men zuò dì tiě qù ba.",
          "exEn": "Let's take the metro."
        }
      ]
    }
  },
  {
    "rank": 22,
    "c": "到",
    "py": "dào",
    "en": "to arrive; to",
    "ex": "我到了。",
    "exPy": "wǒ dào le.",
    "exEn": "I've arrived.",
    "parts": "至 arrive + 刂 knife (≈ <b>dāo</b>, sound)",
    "mnem": "The arrow <b>arrives</b> (至) and the knife (刂) pins the exact spot — you've <b>arrived</b>."
  },
  {
    "rank": 23,
    "c": "以",
    "py": "yǐ",
    "en": "(in 以为: to think, mistakenly)",
    "ex": "我以为你走了。",
    "exPy": "wǒ yǐ wéi nǐ zǒu le.",
    "exEn": "I thought you'd left.",
    "parts": "a person picking up a tool",
    "mnem": "Pick up the tool and work <b>by means of</b> it; 以为 = take it (wrongly) to be so.",
    "lesson": {
      "uses": [
        {
          "g": "“can, may” — by far the most common 以",
          "h": "可以",
          "hPy": "kě yǐ",
          "ex": "这里可以拍照吗？",
          "exPy": "zhè lǐ kě yǐ pāi zhào ma?",
          "exEn": "Can I take photos here?"
        },
        {
          "g": "“to think (wrongly)” — for assumptions that turned out false",
          "h": "以为",
          "hPy": "yǐ wéi",
          "ex": "我以为今天是周五。",
          "exPy": "wǒ yǐ wéi jīn tiān shì zhōu wǔ.",
          "exEn": "I thought today was Friday."
        },
        {
          "g": "“before / after”",
          "h": "以前 / 以后",
          "hPy": "yǐ qián / yǐ hòu",
          "ex": "以后再说吧。",
          "exPy": "yǐ hòu zài shuō ba.",
          "exEn": "Let's talk about it later."
        },
        {
          "g": "“so, therefore”",
          "h": "所以",
          "hPy": "suǒ yǐ",
          "ex": "太晚了，所以我先走了。",
          "exPy": "tài wǎn le, suǒ yǐ wǒ xiān zǒu le.",
          "exEn": "It was too late, so I left."
        }
      ]
    }
  },
  {
    "rank": 24,
    "c": "说",
    "py": "shuō",
    "en": "to say; to speak",
    "ex": "你说什么？",
    "exPy": "nǐ shuō shén me?",
    "exEn": "What did you say?",
    "parts": "讠 speech + 兑 exchange",
    "mnem": "<b>Speech</b> (讠) <b>exchanged</b> (兑) back and forth — to <b>speak</b>."
  },
  {
    "rank": 25,
    "c": "时",
    "py": "shí",
    "en": "time; when (in 有时)",
    "ex": "我有时会迟到。",
    "exPy": "wǒ yǒu shí huì chí dào.",
    "exEn": "I'm sometimes late.",
    "parts": "日 sun + 寸 inch",
    "mnem": "Measuring the <b>sun</b> (日) <b>inch</b> (寸) by inch across the sky — <b>time</b>."
  },
  {
    "rank": 26,
    "c": "要",
    "py": "yào",
    "en": "to want; will",
    "ex": "我要一杯水。",
    "exPy": "wǒ yào yì bēi shuǐ.",
    "exEn": "I want a glass of water.",
    "parts": "西 west + 女 woman",
    "mnem": "The <b>woman</b> (女) from the <b>west</b> (西) knows exactly what she <b>wants</b>.",
    "lesson": {
      "uses": [
        {
          "g": "“to want” something",
          "ex": "我要一份炒饭。",
          "exPy": "wǒ yào yí fèn chǎo fàn.",
          "exEn": "I'll have a fried rice."
        },
        {
          "g": "about to / going to — near future",
          "ex": "电影要开始了。",
          "exPy": "diàn yǐng yào kāi shǐ le.",
          "exEn": "The movie's about to start."
        },
        {
          "g": "“must, need to” — advice and obligations",
          "ex": "开车要小心。",
          "exPy": "kāi chē yào xiǎo xīn.",
          "exEn": "Be careful driving."
        },
        {
          "g": "“if” — colloquial cousin of 如果",
          "h": "要是",
          "hPy": "yào shì",
          "ex": "要是下雨，我们就不去了。",
          "exPy": "yào shì xià yǔ, wǒ men jiù bú qù le.",
          "exEn": "If it rains, we won't go."
        }
      ]
    }
  },
  {
    "rank": 27,
    "c": "就",
    "py": "jiù",
    "en": "just; then (emphasis)",
    "ex": "我马上就到。",
    "exPy": "wǒ mǎ shàng jiù dào.",
    "exEn": "I'll be there right away.",
    "parts": "京 capital + 尤 outstanding",
    "mnem": "Head straight for the <b>capital</b> (京), no detours — <b>right away</b>, <b>just</b> so: 马上就到.",
    "lesson": {
      "uses": [
        {
          "g": "“right away, as soon as” — sooner than expected",
          "ex": "我马上就好。",
          "exPy": "wǒ mǎ shàng jiù hǎo.",
          "exEn": "I'll be ready in a sec."
        },
        {
          "g": "“then” — links a condition to its result",
          "ex": "你累了就休息吧。",
          "exPy": "nǐ lèi le jiù xiū xī ba.",
          "exEn": "If you're tired, then rest."
        },
        {
          "g": "“only, just”",
          "ex": "我就看了一眼。",
          "exPy": "wǒ jiù kàn le yì yǎn.",
          "exEn": "I only took one look."
        },
        {
          "g": "“exactly, precisely” — emphasis",
          "ex": "这就是我想要的！",
          "exPy": "zhè jiù shì wǒ xiǎng yào de!",
          "exEn": "This is exactly what I wanted!"
        }
      ],
      "intro": "Tiny but everywhere — 就 flavors sentences more than it translates."
    }
  },
  {
    "rank": 28,
    "c": "出",
    "py": "chū",
    "en": "to go out; to exit",
    "ex": "我们出去吧。",
    "exPy": "wǒ men chū qù ba.",
    "exEn": "Let's go out.",
    "parts": "山 mountain stacked on 山 mountain",
    "mnem": "Climbing <b>mountain</b> (山) after mountain to get <b>out</b> of the valley."
  },
  {
    "rank": 29,
    "c": "会",
    "py": "huì",
    "en": "can; to know how to; will",
    "ex": "你会说中文吗？",
    "exPy": "nǐ huì shuō zhōng wén ma?",
    "exEn": "Can you speak Chinese?",
    "parts": "人 person + 云 cloud",
    "mnem": "<b>People</b> (人) gathering like <b>clouds</b> (云) — a meeting; skills you've gathered are what you <b>can</b> do.",
    "lesson": {
      "uses": [
        {
          "g": "a learned skill: “know how to”",
          "ex": "我会游泳。",
          "exPy": "wǒ huì yóu yǒng.",
          "exEn": "I can swim."
        },
        {
          "g": "“will (probably)” — predictions",
          "ex": "明天会下雨。",
          "exPy": "míng tiān huì xià yǔ.",
          "exEn": "It'll rain tomorrow."
        },
        {
          "g": "“a little while”",
          "h": "一会儿",
          "hPy": "yí huìr",
          "ex": "等一会儿再走吧。",
          "exPy": "děng yí huìr zài zǒu ba.",
          "exEn": "Let's leave in a little while."
        },
        {
          "g": "a meeting — the noun side of 会",
          "h": "开会",
          "hPy": "kāi huì",
          "ex": "我在开会，晚点儿说。",
          "exPy": "wǒ zài kāi huì, wǎn diǎnr shuō.",
          "exEn": "I'm in a meeting — talk later."
        }
      ]
    }
  },
  {
    "rank": 30,
    "c": "可",
    "py": "kě",
    "en": "can; may (in 可以)",
    "ex": "可以进来吗？",
    "exPy": "kě yǐ jìn lái ma?",
    "exEn": "May I come in?",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 可以 is written kě yǐ but said ké yǐ.",
    "parts": "丁 nail + 口 mouth",
    "mnem": "The <b>mouth</b> (口) nails it down (丁): “<b>Can</b> do — approved!”",
    "lesson": {
      "uses": [
        {
          "g": "“can, may” — permission and possibility",
          "h": "可以",
          "hPy": "kě yǐ",
          "ex": "我可以坐这儿吗？",
          "exPy": "wǒ kě yǐ zuò zhèr ma?",
          "exEn": "May I sit here?"
        },
        {
          "g": "“but, however” — softer than 但是, everywhere in speech",
          "h": "可是",
          "hPy": "kě shì",
          "ex": "我很想去，可是没时间。",
          "exPy": "wǒ hěn xiǎng qù, kě shì méi shí jiān.",
          "exEn": "I really want to go, but I don't have time."
        },
        {
          "g": "可 alone, for emphasis: “really, definitely”",
          "ex": "这可不行！",
          "exPy": "zhè kě bù xíng!",
          "exEn": "That really won't do!"
        },
        {
          "g": "“maybe, possibly” — 可 as “-able” also gives 可爱 cute, 可怕 scary",
          "h": "可能",
          "hPy": "kě néng",
          "ex": "他可能忘了。",
          "exPy": "tā kě néng wàng le.",
          "exEn": "He probably forgot."
        }
      ],
      "intro": "Little 可 does three very different jobs — this is one to slow down on."
    }
  },
  {
    "rank": 31,
    "c": "也",
    "py": "yě",
    "en": "also; too",
    "ex": "我也是。",
    "exPy": "wǒ yě shì.",
    "exEn": "Me too.",
    "parts": "pictograph: a wriggling snake",
    "mnem": "Whatever that wriggly thing is — I want one <b>too</b>! 也 = also."
  },
  {
    "rank": 32,
    "c": "你",
    "py": "nǐ",
    "en": "you",
    "ex": "你好吗？",
    "exPy": "nǐ hǎo ma?",
    "exEn": "How are you?",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 你好 is written nǐ hǎo but said ní hǎo.",
    "parts": "亻 person + 尔 (≈ <b>ní</b>, sound)",
    "mnem": "A <b>person</b> (亻) standing right in front of you — 你 is “<b>you</b>.”"
  },
  {
    "rank": 33,
    "c": "对",
    "py": "duì",
    "en": "correct; towards",
    "ex": "你说得对。",
    "exPy": "nǐ shuō de duì.",
    "exEn": "You're right.",
    "parts": "又 hand + 寸 inch",
    "mnem": "A <b>hand</b> (又) measuring to the exact <b>inch</b> (寸) — precisely <b>correct</b>: 对!",
    "lesson": {
      "uses": [
        {
          "g": "“correct, right”",
          "ex": "对，就是这样！",
          "exPy": "duì, jiù shì zhè yàng!",
          "exEn": "Right, exactly!"
        },
        {
          "g": "“to, towards” someone",
          "h": "对我",
          "hPy": "duì wǒ",
          "ex": "她对我很好。",
          "exPy": "tā duì wǒ hěn hǎo.",
          "exEn": "She treats me really well."
        },
        {
          "g": "“sorry”",
          "h": "对不起",
          "hPy": "duì bu qǐ",
          "ex": "对不起，我来晚了。",
          "exPy": "duì bu qǐ, wǒ lái wǎn le.",
          "exEn": "Sorry I'm late."
        },
        {
          "g": "“oh right, by the way” — topic switcher",
          "h": "对了",
          "hPy": "duì le",
          "ex": "对了，你周末有空吗？",
          "exPy": "duì le, nǐ zhōu mò yǒu kòng ma?",
          "exEn": "Oh right — are you free this weekend?"
        }
      ]
    }
  },
  {
    "rank": 34,
    "c": "生",
    "py": "shēng",
    "en": "life; to be born (in 生日)",
    "ex": "生日快乐！",
    "exPy": "shēng rì kuài lè!",
    "exEn": "Happy birthday!",
    "parts": "pictograph: a sprout on the earth",
    "mnem": "A sprout pushing out of the soil — <b>life</b>, being <b>born</b>: 生日 birth-day."
  },
  {
    "rank": 35,
    "c": "能",
    "py": "néng",
    "en": "can; to be able to",
    "ex": "我能帮你吗？",
    "exPy": "wǒ néng bāng nǐ ma?",
    "exEn": "Can I help you?",
    "parts": "pictograph: a bear (月 body + 匕匕 claws)",
    "mnem": "Originally a <b>bear</b> — strong and capable: <b>can</b>, able to.",
    "lesson": {
      "uses": [
        {
          "g": "can — the circumstances allow it",
          "ex": "我今晚不能来。",
          "exPy": "wǒ jīn wǎn bù néng lái.",
          "exEn": "I can't come tonight."
        },
        {
          "g": "polite requests",
          "ex": "你能帮我一下吗？",
          "exPy": "nǐ néng bāng wǒ yí xià ma?",
          "exEn": "Could you help me out?"
        },
        {
          "g": "能 vs 会 vs 可以: 会 = learned skill, 能 = circumstances allow, 可以 = permission."
        }
      ]
    }
  },
  {
    "rank": 36,
    "c": "而",
    "py": "ér",
    "en": "and also (in 而且)",
    "ex": "他又高又壮，而且很聪明。",
    "exPy": "tā yòu gāo yòu zhuàng, ér qiě hěn cōng míng.",
    "exEn": "He's tall and strong, and also very smart.",
    "parts": "pictograph: a beard",
    "mnem": "A wise man strokes his <b>beard</b> between clauses: “…<b>and</b> moreover…” (而且)."
  },
  {
    "rank": 37,
    "c": "子",
    "py": "zi",
    "en": "(noun suffix)",
    "ex": "这是我儿子。",
    "exPy": "zhè shì wǒ ér zi.",
    "exEn": "This is my son.",
    "parts": "pictograph: a baby with open arms",
    "mnem": "A swaddled <b>baby</b> with arms out — child; also the little suffix on nouns: 儿子, 桌子."
  },
  {
    "rank": 38,
    "c": "那",
    "py": "nà",
    "en": "that",
    "ex": "那是谁？",
    "exPy": "nà shì shuí?",
    "exEn": "Who is that?",
    "parts": "刀-shape + 阝 city",
    "mnem": "Pointing at the <b>city</b> (阝) on the horizon — <b>that</b> one over there."
  },
  {
    "rank": 39,
    "c": "得",
    "py": "dé",
    "en": "to get; to obtain",
    "ex": "我得到了好消息。",
    "exPy": "wǒ dé dào le hǎo xiāo xī.",
    "exEn": "I got good news.",
    "parts": "彳 step + 旦 dawn + 寸 inch",
    "mnem": "<b>Step</b> (彳) out at <b>dawn</b> (旦) and come home with treasure in <b>hand</b> (寸) — to <b>get</b>: 得到.",
    "lesson": {
      "uses": [
        {
          "g": "dé — to get, to obtain",
          "h": "得到",
          "hPy": "dé dào",
          "ex": "他得到了大家的信任。",
          "exPy": "tā dé dào le dà jiā de xìn rèn.",
          "exEn": "He earned everyone's trust."
        },
        {
          "g": "de — verb + 得 + how well: manner or degree",
          "h": "跑得快",
          "hPy": "pǎo de kuài",
          "ex": "你跑得真快！",
          "exPy": "nǐ pǎo de zhēn kuài!",
          "exEn": "You run so fast!"
        },
        {
          "g": "děi — “must, gotta” (colloquial)",
          "h": "得走了",
          "hPy": "děi zǒu le",
          "ex": "我得走了。",
          "exPy": "wǒ děi zǒu le.",
          "exEn": "I've gotta go."
        }
      ],
      "intro": "Three readings, three jobs — the classic triple-duty character."
    }
  },
  {
    "rank": 40,
    "c": "于",
    "py": "yú",
    "en": "(formal: in, at; in 取决于)",
    "ex": "这取决于你。",
    "exPy": "zhè qǔ jué yú nǐ.",
    "exEn": "It depends on you.",
    "parts": "a simple signpost",
    "mnem": "A little signpost pinning a phrase to its place — <b>at/in</b> (formal): 取决于 depends <b>on</b>."
  },
  {
    "rank": 41,
    "c": "着",
    "py": "zhe",
    "en": "(progressive aspect particle)",
    "ex": "我在等着你。",
    "exPy": "wǒ zài děng zhe nǐ.",
    "exEn": "I'm waiting for you.",
    "parts": "羊 sheep + 目 eye",
    "mnem": "Your <b>eye</b> (目) fixed on the <b>sheep</b> (羊), continuously — the “-ing” particle: 等着 waiting.",
    "lesson": {
      "uses": [
        {
          "g": "zhe — an ongoing state: something stays that way",
          "ex": "别站着，坐吧。",
          "exPy": "bié zhàn zhe, zuò ba.",
          "exEn": "Don't just stand there — sit."
        },
        {
          "g": "zhe — doing one thing while doing another",
          "h": "V着V",
          "hPy": "V zhe V",
          "ex": "我们走着去吧。",
          "exPy": "wǒ men zǒu zhe qù ba.",
          "exEn": "Let's walk there."
        },
        {
          "g": "zháo — after a verb: managed to (睡着 = fall asleep)",
          "h": "睡不着",
          "hPy": "shuì bù zháo",
          "ex": "我昨晚睡不着。",
          "exPy": "wǒ zuó wǎn shuì bù zháo.",
          "exEn": "I couldn't fall asleep last night."
        },
        {
          "g": "zháo also in 着急 “worried, anxious”",
          "h": "着急",
          "hPy": "zháo jí",
          "ex": "别着急，慢慢来。",
          "exPy": "bié zháo jí, màn màn lái.",
          "exEn": "No rush — take your time."
        }
      ]
    }
  },
  {
    "rank": 42,
    "c": "下",
    "py": "xià",
    "en": "under; below; next",
    "ex": "下雨了。",
    "exPy": "xià yǔ le.",
    "exEn": "It's raining.",
    "parts": "a mark below the base line",
    "mnem": "A root growing <b>below</b> the ground line — <b>down</b>, under: 下雨 rain comes down.",
    "lesson": {
      "uses": [
        {
          "g": "“next” with time words",
          "h": "下个",
          "hPy": "xià gè",
          "ex": "下个月我去中国。",
          "exPy": "xià gè yuè wǒ qù zhōng guó.",
          "exEn": "Next month I'm going to China."
        },
        {
          "g": "to get off / go down",
          "h": "下车",
          "hPy": "xià chē",
          "ex": "我们下一站下车。",
          "exPy": "wǒ men xià yí zhàn xià chē.",
          "exEn": "We get off at the next stop."
        },
        {
          "g": "verb + 一下: “real quick”",
          "h": "一下",
          "hPy": "yí xià",
          "ex": "我看一下。",
          "exPy": "wǒ kàn yí xià.",
          "exEn": "Let me take a quick look."
        }
      ]
    }
  },
  {
    "rank": 43,
    "c": "自",
    "py": "zì",
    "en": "self (in 自己)",
    "ex": "我自己来。",
    "exPy": "wǒ zì jǐ lái.",
    "exEn": "I'll do it myself.",
    "parts": "pictograph: a nose",
    "mnem": "A <b>nose</b> — Chinese speakers point at their nose to say “me”: <b>self</b> (自己)."
  },
  {
    "rank": 44,
    "c": "之",
    "py": "zhī",
    "en": "(formal connector, in 总之)",
    "ex": "总之，我同意。",
    "exPy": "zǒng zhī, wǒ tóng yì.",
    "exEn": "In short, I agree.",
    "parts": "pictograph: a footprint",
    "mnem": "A classical <b>footstep</b> linking one thing to the next — the old-style 的: 总之 in a word."
  },
  {
    "rank": 45,
    "c": "年",
    "py": "nián",
    "en": "year",
    "ex": "明年见！",
    "exPy": "míng nián jiàn!",
    "exEn": "See you next year!",
    "parts": "a person carrying grain",
    "mnem": "A farmer carrying home the <b>harvest</b> — one harvest = one <b>year</b>."
  },
  {
    "rank": 46,
    "c": "过",
    "py": "guò",
    "en": "to pass; (experienced-action particle)",
    "ex": "我去过北京。",
    "exPy": "wǒ qù guò běi jīng.",
    "exEn": "I've been to Beijing.",
    "parts": "辶 walk + 寸 inch",
    "mnem": "<b>Walking</b> (辶) past, inch (寸) by inch — to <b>cross</b>; once crossed it's experience: 去过 have been.",
    "lesson": {
      "uses": [
        {
          "g": "to cross, to pass",
          "ex": "过马路要小心。",
          "exPy": "guò mǎ lù yào xiǎo xīn.",
          "exEn": "Be careful crossing the street."
        },
        {
          "g": "verb + 过: “have ever done” — life experience",
          "h": "吃过",
          "hPy": "chī guò",
          "ex": "你吃过北京烤鸭吗？",
          "exPy": "nǐ chī guò běi jīng kǎo yā ma?",
          "exEn": "Have you ever had Peking duck?"
        },
        {
          "g": "with time: after, in (some days)",
          "ex": "过两天再说。",
          "exPy": "guò liǎng tiān zài shuō.",
          "exEn": "Let's revisit in a couple of days."
        }
      ]
    }
  },
  {
    "rank": 47,
    "c": "发",
    "py": "fā",
    "en": "to send; to issue",
    "ex": "我发给你了。",
    "exPy": "wǒ fā gěi nǐ le.",
    "exEn": "I sent it to you.",
    "parts": "又 hand + strokes flying off",
    "mnem": "A <b>hand</b> (又) letting the arrow fly — to <b>send out</b>: 发消息 send a message."
  },
  {
    "rank": 48,
    "c": "后",
    "py": "hòu",
    "en": "after; behind",
    "ex": "放学后见。",
    "exPy": "fàng xué hòu jiàn.",
    "exEn": "See you after school.",
    "parts": "厂 slope + 口 mouth",
    "mnem": "The voice (口) calling from <b>behind</b> the hill (厂) — <b>after</b>, behind: 以后 afterwards."
  },
  {
    "rank": 49,
    "c": "作",
    "py": "zuò",
    "en": "to do; to make (in 工作)",
    "ex": "我在工作。",
    "exPy": "wǒ zài gōng zuò.",
    "exEn": "I'm working.",
    "parts": "亻 person + 乍 (≈ <b>zhà</b>, sound)",
    "mnem": "A <b>person</b> (亻) springing suddenly (乍) into action — to <b>do</b>, to make: 工作 work."
  },
  {
    "rank": 50,
    "c": "里",
    "py": "lǐ",
    "en": "inside; in",
    "ex": "我在家里。",
    "exPy": "wǒ zài jiā lǐ.",
    "exEn": "I'm at home (inside).",
    "parts": "田 field + 土 earth",
    "mnem": "<b>Fields</b> (田) on <b>earth</b> (土) — the village you live <b>in</b>: inside."
  },
  {
    "rank": 51,
    "c": "用",
    "py": "yòng",
    "en": "to use",
    "ex": "你会用这个吗？",
    "exPy": "nǐ huì yòng zhè ge ma?",
    "exEn": "Do you know how to use this?",
    "parts": "pictograph: a bucket",
    "mnem": "An old wooden bucket — grab it and put it to <b>use</b>."
  },
  {
    "rank": 52,
    "c": "道",
    "py": "dào",
    "en": "way; to say (in 知道)",
    "ex": "我知道了。",
    "exPy": "wǒ zhī dào le.",
    "exEn": "Got it.",
    "parts": "辶 walk + 首 head",
    "mnem": "Your <b>head</b> (首) leading your feet (辶) down the <b>path</b> — the way; 知道 = know the way."
  },
  {
    "rank": 53,
    "c": "行",
    "py": "xíng",
    "en": "OK; to walk; to be alright",
    "ex": "行，就这么办。",
    "exPy": "xíng, jiù zhè me bàn.",
    "exEn": "OK, let's do it that way.",
    "parts": "pictograph: a crossroads",
    "mnem": "A <b>crossroads</b> where everything moves — to go; “行!” = it works, OK, let's go.",
    "lesson": {
      "uses": [
        {
          "g": "xíng — “OK, that works”",
          "ex": "行，就这么定了。",
          "exPy": "xíng, jiù zhè me dìng le.",
          "exEn": "OK, it's settled."
        },
        {
          "g": "xíng — to go, travel: the “self-go vehicle”, a bike",
          "h": "自行车",
          "hPy": "zì xíng chē",
          "ex": "我骑自行车上班。",
          "exPy": "wǒ qí zì xíng chē shàng bān.",
          "exEn": "I bike to work."
        },
        {
          "g": "háng — row; trade; read háng in 银行 “bank”",
          "h": "银行",
          "hPy": "yín háng",
          "ex": "银行几点开门？",
          "exPy": "yín háng jǐ diǎn kāi mén?",
          "exEn": "What time does the bank open?"
        }
      ]
    }
  },
  {
    "rank": 54,
    "c": "所",
    "py": "suǒ",
    "en": "place (in 所以)",
    "ex": "所以我没去。",
    "exPy": "suǒ yǐ wǒ méi qù.",
    "exEn": "So I didn't go.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 所以 is written suǒ yǐ but said suó yǐ.",
    "parts": "户 door + 斤 axe",
    "mnem": "The <b>door</b> (户) where the <b>axe</b> (斤) hangs — the <b>place</b>; 所以: from that place follows… <b>so</b>.",
    "lesson": {
      "uses": [
        {
          "g": "“so, therefore” — by far the most common use",
          "h": "所以",
          "hPy": "suǒ yǐ",
          "ex": "我没带伞，所以淋湿了。",
          "exPy": "wǒ méi dài sǎn, suǒ yǐ lín shī le.",
          "exEn": "I didn't bring an umbrella, so I got soaked."
        },
        {
          "g": "“toilet” — the other 所 you need daily",
          "h": "厕所",
          "hPy": "cè suǒ",
          "ex": "请问，厕所在哪儿？",
          "exPy": "qǐng wèn, cè suǒ zài nǎr?",
          "exEn": "Excuse me, where's the bathroom?"
        },
        {
          "g": "“all, every”",
          "h": "所有",
          "hPy": "suǒ yǒu",
          "ex": "所有人都到了。",
          "exPy": "suǒ yǒu rén dōu dào le.",
          "exEn": "Everyone's here."
        }
      ]
    }
  },
  {
    "rank": 55,
    "c": "然",
    "py": "rán",
    "en": "so; like that (in 然后)",
    "ex": "然后呢？",
    "exPy": "rán hòu ne?",
    "exEn": "And then what?",
    "parts": "月 meat + 犬 dog + 灬 fire",
    "mnem": "Meat roasting over the <b>fire</b> (灬) — “<b>so</b> it is, naturally”; 然后 = after that."
  },
  {
    "rank": 56,
    "c": "家",
    "py": "jiā",
    "en": "home; family",
    "ex": "我要回家了。",
    "exPy": "wǒ yào huí jiā le.",
    "exEn": "I'm heading home.",
    "parts": "宀 roof + 豕 pig",
    "mnem": "A <b>pig</b> (豕) under your <b>roof</b> (宀) — wealth and warmth: <b>home</b>."
  },
  {
    "rank": 57,
    "c": "种",
    "py": "zhǒng",
    "en": "kind; type; to plant",
    "ex": "这种事很常见。",
    "exPy": "zhè zhǒng shì hěn cháng jiàn.",
    "exEn": "This kind of thing is common.",
    "parts": "禾 grain + 中 (≈ <b>zhōng</b>, sound)",
    "mnem": "Each <b>grain</b> (禾) is its own <b>kind</b> of seed — 这种 this kind; plant it and it's 种 zhòng, to sow."
  },
  {
    "rank": 58,
    "c": "事",
    "py": "shì",
    "en": "matter; thing; affair",
    "ex": "没事儿。",
    "exPy": "méi shìr.",
    "exEn": "It's nothing; no worries.",
    "parts": "a hand holding a writing tablet",
    "mnem": "A hand holding the official record — the <b>matter</b> at hand; 没事 = nothing on record, no worries."
  },
  {
    "rank": 59,
    "c": "成",
    "py": "chéng",
    "en": "to become; to succeed",
    "ex": "我们成功了！",
    "exPy": "wǒ men chéng gōng le!",
    "exEn": "We did it!",
    "parts": "戈 weapon, forged complete",
    "mnem": "The <b>weapon</b> (戈) comes off the forge finished — to <b>become</b>, to succeed: 成功."
  },
  {
    "rank": 60,
    "c": "方",
    "py": "fāng",
    "en": "square; place (in 地方)",
    "ex": "这个地方真漂亮。",
    "exPy": "zhè ge dì fāng zhēn piào liàng.",
    "exEn": "This place is really pretty.",
    "parts": "pictograph: a square with corners",
    "mnem": "A <b>square</b> pointing all four directions — 地方: a place on the map."
  },
  {
    "rank": 61,
    "c": "多",
    "py": "duō",
    "en": "many; much",
    "ex": "你多大了？",
    "exPy": "nǐ duō dà le?",
    "exEn": "How old are you?",
    "parts": "夕 evening + 夕 evening",
    "mnem": "<b>Evening</b> (夕) after evening piling up — <b>many</b>, much.",
    "lesson": {
      "uses": [
        {
          "g": "“many, much”",
          "ex": "今天人真多！",
          "exPy": "jīn tiān rén zhēn duō!",
          "exEn": "It's so crowded today!"
        },
        {
          "g": "asks “how …?”",
          "h": "多 + adj",
          "hPy": "duō + adj",
          "ex": "你多高？",
          "exPy": "nǐ duō gāo?",
          "exEn": "How tall are you?"
        },
        {
          "g": "“how many / how much”",
          "h": "多少",
          "hPy": "duō shǎo",
          "ex": "你的电话是多少？",
          "exPy": "nǐ de diàn huà shì duō shǎo?",
          "exEn": "What's your phone number?"
        },
        {
          "g": "“(do) more”",
          "h": "多 + verb",
          "hPy": "duō + verb",
          "ex": "多喝水，早点儿睡。",
          "exPy": "duō hē shuǐ, zǎo diǎnr shuì.",
          "exEn": "Drink more water and sleep early."
        }
      ]
    }
  },
  {
    "rank": 62,
    "c": "经",
    "py": "jīng",
    "en": "to pass through (in 已经)",
    "ex": "我已经吃了。",
    "exPy": "wǒ yǐ jīng chī le.",
    "exEn": "I've already eaten.",
    "parts": "纟 silk + loom warp",
    "mnem": "The <b>silk</b> (纟) warp threads of a loom — everything <b>passes through</b> them: 已经 already passed."
  },
  {
    "rank": 63,
    "c": "么",
    "py": "me",
    "en": "(question suffix, in 什么/怎么)",
    "ex": "你在干什么？",
    "exPy": "nǐ zài gàn shén me?",
    "exEn": "What are you doing?",
    "parts": "a tiny silk thread",
    "mnem": "A tiny dangling <b>thread</b> tacked onto question words: 什么? 怎么?"
  },
  {
    "rank": 64,
    "c": "去",
    "py": "qù",
    "en": "to go",
    "ex": "你要去哪儿？",
    "exPy": "nǐ yào qù nǎr?",
    "exEn": "Where are you going?",
    "parts": "土 earth + 厶 private",
    "mnem": "Pack your <b>private</b> (厶) things and leave this patch of <b>earth</b> (土) — to <b>go</b>."
  },
  {
    "rank": 65,
    "c": "法",
    "py": "fǎ",
    "en": "method (in 办法)",
    "ex": "有什么办法吗？",
    "exPy": "yǒu shén me bàn fǎ ma?",
    "exEn": "Is there any way to solve this?",
    "parts": "氵 water + 去 go",
    "mnem": "<b>Law</b> should flow like <b>water</b> (氵) — level and fair; 办法: the way water finds through."
  },
  {
    "rank": 66,
    "c": "学",
    "py": "xué",
    "en": "to study; to learn",
    "ex": "我在学中文。",
    "exPy": "wǒ zài xué zhōng wén.",
    "exEn": "I'm learning Chinese.",
    "parts": "hands pouring in + 子 child under a roof",
    "mnem": "Hands pouring knowledge over a <b>child</b> (子) under the school roof — to <b>learn</b>."
  },
  {
    "rank": 67,
    "c": "如",
    "py": "rú",
    "en": "if; like (in 如果)",
    "ex": "如果你忙，就别来了。",
    "exPy": "rú guǒ nǐ máng, jiù bié lái le.",
    "exEn": "If you're busy, don't bother coming.",
    "parts": "女 woman + 口 mouth",
    "mnem": "Do <b>as</b> the wise woman (女) says (口) — like, as, <b>if</b>: 如果."
  },
  {
    "rank": 68,
    "c": "都",
    "py": "dōu",
    "en": "all; both",
    "ex": "我们都到了。",
    "exPy": "wǒ men dōu dào le.",
    "exEn": "We've all arrived.",
    "parts": "者 + 阝 city",
    "mnem": "The capital <b>city</b> (阝) where everyone gathers — <b>all</b>: 我们都.",
    "lesson": {
      "uses": [
        {
          "g": "“all, both” — comes after the things it covers",
          "ex": "我们都饿了。",
          "exPy": "wǒ men dōu è le.",
          "exEn": "We're all hungry."
        },
        {
          "g": "“even …”",
          "h": "连……都",
          "hPy": "lián … dōu",
          "ex": "他连早饭都没吃。",
          "exPy": "tā lián zǎo fàn dōu méi chī.",
          "exEn": "He didn't even eat breakfast."
        },
        {
          "g": "“already …!” — mild disbelief",
          "h": "都……了",
          "hPy": "dōu … le",
          "ex": "都十二点了，快睡吧！",
          "exPy": "dōu shí èr diǎn le, kuài shuì ba!",
          "exEn": "It's already midnight — go to sleep!"
        },
        {
          "g": "read dū in 首都 “capital city”",
          "h": "首都",
          "hPy": "shǒu dū",
          "ex": "北京是中国的首都。",
          "exPy": "běi jīng shì zhōng guó de shǒu dū.",
          "exEn": "Beijing is China's capital."
        }
      ]
    }
  },
  {
    "rank": 69,
    "c": "同",
    "py": "tóng",
    "en": "same; together (in 同学)",
    "ex": "我们是同学。",
    "exPy": "wǒ men shì tóng xué.",
    "exEn": "We're classmates.",
    "parts": "一 one + 口 mouth under one frame",
    "mnem": "Everyone under one roof-frame speaking with <b>one mouth</b> (口) — the <b>same</b>: 同学 study-mates."
  },
  {
    "rank": 70,
    "c": "现",
    "py": "xiàn",
    "en": "now (in 现在)",
    "ex": "你现在在哪儿？",
    "exPy": "nǐ xiàn zài zài nǎr?",
    "exEn": "Where are you right now?",
    "parts": "王 jade + 见 see",
    "mnem": "<b>Jade</b> (王) suddenly <b>seen</b> (见) sparkling — it appears right <b>now</b>: 现在."
  },
  {
    "rank": 71,
    "c": "当",
    "py": "dāng",
    "en": "of course (in 当然); to serve as",
    "ex": "那当然！",
    "exPy": "nà dāng rán!",
    "exEn": "Of course!",
    "parts": "彐 broom-hand over a base",
    "mnem": "Pick up the broom and <b>serve as</b> the one in charge — 当医生 work as a doctor; 当然 of course, as one should.",
    "lesson": {
      "uses": [
        {
          "g": "dāng — to work as, to serve as",
          "ex": "她想当医生。",
          "exPy": "tā xiǎng dāng yī shēng.",
          "exEn": "She wants to be a doctor."
        },
        {
          "g": "“of course”",
          "h": "当然",
          "hPy": "dāng rán",
          "ex": "当然没问题！",
          "exPy": "dāng rán méi wèn tí!",
          "exEn": "Of course, no problem!"
        },
        {
          "g": "dàng (4th tone) — 上当 “to get fooled / scammed”",
          "h": "上当",
          "hPy": "shàng dàng",
          "ex": "我上当了！",
          "exPy": "wǒ shàng dàng le!",
          "exEn": "I got scammed!"
        }
      ]
    }
  },
  {
    "rank": 72,
    "c": "没",
    "py": "méi",
    "en": "not (have); did not",
    "ex": "我没听懂。",
    "exPy": "wǒ méi tīng dǒng.",
    "exEn": "I didn't understand.",
    "parts": "氵 water + 殳 tool",
    "mnem": "It sank into the <b>water</b> (氵) — gone: <b>not have</b>, didn't happen: 没有."
  },
  {
    "rank": 73,
    "c": "动",
    "py": "dòng",
    "en": "to move; to act",
    "ex": "别动！",
    "exPy": "bié dòng!",
    "exEn": "Don't move!",
    "parts": "云 cloud + 力 force",
    "mnem": "<b>Force</b> (力) pushing the <b>clouds</b> (云) across the sky — things <b>move</b>: 别动! don't move!"
  },
  {
    "rank": 74,
    "c": "面",
    "py": "miàn",
    "en": "face; side; noodles",
    "ex": "我们见面聊吧。",
    "exPy": "wǒ men jiàn miàn liáo ba.",
    "exEn": "Let's meet up and talk.",
    "parts": "pictograph: a face in a frame",
    "mnem": "A <b>face</b> — face, surface, side; 见面: see each other's faces, meet. (Also noodles: 面条.)"
  },
  {
    "rank": 75,
    "c": "起",
    "py": "qǐ",
    "en": "to rise; up (in 一起)",
    "ex": "我们一起去吧。",
    "exPy": "wǒ men yì qǐ qù ba.",
    "exEn": "Let's go together.",
    "parts": "走 walk + 己 self (≈ <b>jǐ</b>, sound)",
    "mnem": "Get your<b>self</b> (己) up and <b>walking</b> (走) — to <b>rise</b>; 一起 = rise as one, together."
  },
  {
    "rank": 76,
    "c": "看",
    "py": "kàn",
    "en": "to look; to watch; to read",
    "ex": "你在看什么？",
    "exPy": "nǐ zài kàn shén me?",
    "exEn": "What are you watching?",
    "parts": "手 hand + 目 eye",
    "mnem": "A <b>hand</b> (手) shading the <b>eyes</b> (目) to peer into the distance — to <b>look</b>."
  },
  {
    "rank": 77,
    "c": "定",
    "py": "dìng",
    "en": "surely (in 一定); to decide",
    "ex": "我一定会去。",
    "exPy": "wǒ yí dìng huì qù.",
    "exEn": "I will definitely go.",
    "parts": "宀 roof + a straightened base",
    "mnem": "Everything set straight under the <b>roof</b> (宀) — settled, <b>fixed</b>: 一定 for sure."
  },
  {
    "rank": 78,
    "c": "天",
    "py": "tiān",
    "en": "day; sky",
    "ex": "今天天气真好。",
    "exPy": "jīn tiān tiān qì zhēn hǎo.",
    "exEn": "The weather's really nice today.",
    "parts": "大 big person + 一 line above",
    "mnem": "The line <b>above</b> even the biggest person (大) — the <b>sky</b>; each sky-cycle is a <b>day</b>."
  },
  {
    "rank": 79,
    "c": "分",
    "py": "fēn",
    "en": "to divide; minute; point",
    "ex": "还有五分钟。",
    "exPy": "hái yǒu wǔ fēn zhōng.",
    "exEn": "There are five more minutes.",
    "parts": "八 split + 刀 knife",
    "mnem": "A <b>knife</b> (刀) cutting a thing in <b>two</b> (八) — to divide; a <b>minute</b> is a slice of the hour."
  },
  {
    "rank": 80,
    "c": "还",
    "py": "hái",
    "en": "still; also; even more",
    "ex": "你还好吗？",
    "exPy": "nǐ hái hǎo ma?",
    "exEn": "Are you okay?",
    "parts": "辶 walk + 不 no",
    "mnem": "<b>Walking</b> (辶) back, “<b>not</b> (不) done yet” — <b>still</b>, also: 还好 still OK.",
    "lesson": {
      "uses": [
        {
          "g": "hái — “still”",
          "ex": "他还没起床。",
          "exPy": "tā hái méi qǐ chuáng.",
          "exEn": "He still hasn't gotten up."
        },
        {
          "g": "hái — “also, in addition”",
          "ex": "你还要别的吗？",
          "exPy": "nǐ hái yào bié de ma?",
          "exEn": "Do you want anything else?"
        },
        {
          "g": "“or” in questions; also “had better”",
          "h": "还是",
          "hPy": "hái shì",
          "ex": "你喝茶还是咖啡？",
          "exPy": "nǐ hē chá hái shì kā fēi?",
          "exEn": "Tea or coffee?"
        },
        {
          "g": "huán — to return, to give back",
          "h": "还钱",
          "hPy": "huán qián",
          "ex": "我下个月还钱。",
          "exPy": "wǒ xià gè yuè huán qián.",
          "exEn": "I'll pay the money back next month."
        }
      ]
    }
  },
  {
    "rank": 81,
    "c": "进",
    "py": "jìn",
    "en": "to enter",
    "ex": "请进！",
    "exPy": "qǐng jìn!",
    "exEn": "Please come in!",
    "parts": "辶 walk + 井 well",
    "mnem": "<b>Walk</b> (辶) toward the <b>well</b> (井) at the village center — to <b>enter</b>: 请进!"
  },
  {
    "rank": 82,
    "c": "好",
    "py": "hǎo",
    "en": "good; well; OK",
    "ex": "好的，没问题！",
    "exPy": "hǎo de, méi wèn tí!",
    "exEn": "OK, no problem!",
    "parts": "女 woman + 子 child",
    "mnem": "A <b>woman</b> (女) holding her <b>child</b> (子) — mother and child together: everything is <b>good</b>.",
    "lesson": {
      "uses": [
        {
          "g": "“good; fine” — also the all-purpose “OK”",
          "ex": "好，就这样吧。",
          "exPy": "hǎo, jiù zhè yàng ba.",
          "exEn": "OK, let's leave it at that."
        },
        {
          "g": "“so …!”",
          "h": "好 + adj",
          "hPy": "hǎo + adj",
          "ex": "今天好热啊！",
          "exPy": "jīn tiān hǎo rè a!",
          "exEn": "It's so hot today!"
        },
        {
          "g": "easy / nice to …",
          "h": "好 + verb",
          "hPy": "hǎo + verb",
          "ex": "这个很好用。",
          "exPy": "zhè ge hěn hǎo yòng.",
          "exEn": "This works really well."
        },
        {
          "g": "hào (4th tone) — “to be fond of”: 爱好 hobby",
          "h": "爱好",
          "hPy": "ài hào",
          "ex": "你有什么爱好？",
          "exPy": "nǐ yǒu shén me ài hào?",
          "exEn": "What are your hobbies?"
        }
      ]
    }
  },
  {
    "rank": 83,
    "c": "小",
    "py": "xiǎo",
    "en": "small; little",
    "ex": "这只是小事。",
    "exPy": "zhè zhǐ shì xiǎo shì.",
    "exEn": "It's just a small thing.",
    "parts": "a hook splitting two tiny dots",
    "mnem": "One stroke splitting a thing into two tiny bits — <b>small</b>."
  },
  {
    "rank": 84,
    "c": "部",
    "py": "bù",
    "en": "part; unit (measure word for films)",
    "ex": "这部电影很好看。",
    "exPy": "zhè bù diàn yǐng hěn hǎo kàn.",
    "exEn": "This movie is really good.",
    "parts": "咅 (≈ sound) + 阝 city",
    "mnem": "A <b>city</b> (阝) split into districts — a <b>part</b>, a section; also the measure word for films."
  },
  {
    "rank": 85,
    "c": "其",
    "py": "qí",
    "en": "actually (in 其实)",
    "ex": "其实我不太喜欢。",
    "exPy": "qí shí wǒ bú tài xǐ huān.",
    "exEn": "Actually, I don't really like it.",
    "parts": "pictograph: a winnowing basket",
    "mnem": "Pointing at the basket: “<b>its</b> contents, <b>that</b> one” — 其实: as for the actual facts…"
  },
  {
    "rank": 86,
    "c": "些",
    "py": "xiē",
    "en": "some; a few",
    "ex": "你要不要吃一些？",
    "exPy": "nǐ yào bú yào chī yì xiē?",
    "exEn": "Do you want to eat some?",
    "parts": "此 this + 二 two",
    "mnem": "<b>This</b> (此) plus another one or <b>two</b> (二) — <b>some</b>, a few."
  },
  {
    "rank": 87,
    "c": "主",
    "py": "zhǔ",
    "en": "main (in 主意)",
    "ex": "这是个好主意！",
    "exPy": "zhè shì gè hǎo zhǔ yì!",
    "exEn": "That's a good idea!",
    "parts": "丶 flame + 王 king",
    "mnem": "The <b>flame</b> (丶) burning above the king (王) — the <b>master</b> of the house keeps the lamp; 主意: the master's <b>idea</b>."
  },
  {
    "rank": 88,
    "c": "样",
    "py": "yàng",
    "en": "kind; way (in 这样/怎么样)",
    "ex": "你觉得怎么样？",
    "exPy": "nǐ jué de zěn me yàng?",
    "exEn": "What do you think?",
    "parts": "木 wood + 羊 sheep (≈ <b>yáng</b>, sound)",
    "mnem": "A <b>wooden</b> (木) mold shaped like a <b>sheep</b> (羊) — a pattern, a <b>way</b>: 怎么样? what's it like?"
  },
  {
    "rank": 89,
    "c": "理",
    "py": "lǐ",
    "en": "reason; sense (in 道理)",
    "ex": "你说得有道理。",
    "exPy": "nǐ shuō de yǒu dào lǐ.",
    "exEn": "What you said makes sense.",
    "parts": "王 jade + 里 (≈ <b>lǐ</b>, sound)",
    "mnem": "Carving <b>jade</b> (王) along its natural veins — following the inner <b>logic</b>: 道理 sense."
  },
  {
    "rank": 90,
    "c": "心",
    "py": "xīn",
    "en": "heart; mind",
    "ex": "别担心。",
    "exPy": "bié dān xīn.",
    "exEn": "Don't worry.",
    "parts": "pictograph: a heart",
    "mnem": "A <b>heart</b> with three drops of blood — heart, mind; 担心 = a weighed-down heart: worry."
  },
  {
    "rank": 91,
    "c": "她",
    "py": "tā",
    "en": "she; her",
    "ex": "她是谁？",
    "exPy": "tā shì shuí?",
    "exEn": "Who is she?",
    "parts": "女 woman + 也 also",
    "mnem": "Just like 他, but with <b>woman</b> (女) — <b>she</b>."
  },
  {
    "rank": 92,
    "c": "本",
    "py": "běn",
    "en": "originally (in 本来)",
    "ex": "我本来想去。",
    "exPy": "wǒ běn lái xiǎng qù.",
    "exEn": "I originally wanted to go.",
    "parts": "木 tree + 一 mark at the root",
    "mnem": "A stroke marking the tree's (木) <b>root</b> — the origin: 本来 = from the root, originally."
  },
  {
    "rank": 93,
    "c": "前",
    "py": "qián",
    "en": "front; before; ago",
    "ex": "你以前来过吗？",
    "exPy": "nǐ yǐ qián lái guò ma?",
    "exEn": "Have you been here before?",
    "parts": "the prow of a boat cutting ahead",
    "mnem": "A boat's prow cutting <b>forward</b> — in front, <b>before</b>: 以前 = the stretch already sailed."
  },
  {
    "rank": 94,
    "c": "开",
    "py": "kāi",
    "en": "to open; to start; to drive",
    "ex": "快开门！",
    "exPy": "kuài kāi mén!",
    "exEn": "Open the door, quick!",
    "parts": "一 bar + 廾 two hands",
    "mnem": "Two hands (廾) lifting the <b>bar</b> (一) off the door — to <b>open</b>; 开车: open the throttle, drive."
  },
  {
    "rank": 95,
    "c": "但",
    "py": "dàn",
    "en": "but; however",
    "ex": "我很累，但是很开心。",
    "exPy": "wǒ hěn lèi, dàn shì hěn kāi xīn.",
    "exEn": "I'm tired, but happy.",
    "parts": "亻 person + 旦 dawn (≈ <b>dàn</b>, sound)",
    "mnem": "At <b>dawn</b> (旦) the person (亻) adds: “<b>but</b> one more thing…” — 但是."
  },
  {
    "rank": 96,
    "c": "因",
    "py": "yīn",
    "en": "because (of) (in 因为)",
    "ex": "因为下雨，我没去。",
    "exPy": "yīn wèi xià yǔ, wǒ méi qù.",
    "exEn": "I didn't go because it was raining.",
    "parts": "大 person inside 囗 box",
    "mnem": "The <b>person</b> (大) found inside the sealed box (囗) — there's your <b>cause</b>: 因为 because."
  },
  {
    "rank": 97,
    "c": "只",
    "py": "zhǐ",
    "en": "only; just",
    "ex": "我只是问问。",
    "exPy": "wǒ zhǐ shì wèn wèn.",
    "exEn": "I'm just asking.",
    "parts": "口 mouth + 八 a puff of breath",
    "mnem": "One mouth (口), one puff (八) — <b>only</b> that, <b>just</b>: 只是.",
    "lesson": {
      "uses": [
        {
          "g": "zhǐ — “only, just”",
          "ex": "我只有十块钱。",
          "exPy": "wǒ zhǐ yǒu shí kuài qián.",
          "exEn": "I've only got ten kuai."
        },
        {
          "g": "zhī — measure word for animals (and one of a pair)",
          "h": "一只",
          "hPy": "yì zhī",
          "ex": "我家有两只猫。",
          "exPy": "wǒ jiā yǒu liǎng zhī māo.",
          "exEn": "I have two cats."
        }
      ]
    }
  },
  {
    "rank": 98,
    "c": "从",
    "py": "cóng",
    "en": "from",
    "ex": "你从哪儿来？",
    "exPy": "nǐ cóng nǎr lái?",
    "exEn": "Where are you from?",
    "parts": "人 person + 人 person",
    "mnem": "One person walking behind another — to follow; where you follow <b>from</b>: 你从哪儿来?"
  },
  {
    "rank": 99,
    "c": "想",
    "py": "xiǎng",
    "en": "to think; to want; to miss",
    "ex": "我想你了。",
    "exPy": "wǒ xiǎng nǐ le.",
    "exEn": "I miss you.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 想你 is written xiǎng nǐ but said xiáng nǐ.",
    "parts": "木 tree + 目 eye + 心 heart",
    "mnem": "Your <b>eye</b> (目) on a distant tree (木), your <b>heart</b> (心) underneath — to <b>think</b> of, to <b>miss</b>."
  },
  {
    "rank": 100,
    "c": "实",
    "py": "shí",
    "en": "real; true (in 其实/说实话)",
    "ex": "说实话，我不知道。",
    "exPy": "shuō shí huà, wǒ bù zhī dào.",
    "exEn": "To be honest, I don't know.",
    "parts": "宀 roof + 头 head",
    "mnem": "Real goods piled head-high (头) under the <b>roof</b> (宀) — solid, <b>real</b>: 其实 actually."
  },
  {
    "rank": 101,
    "c": "日",
    "py": "rì",
    "en": "sun; day",
    "ex": "今天是几月几日？",
    "exPy": "jīn tiān shì jǐ yuè jǐ rì?",
    "exEn": "What's today's date?",
    "parts": "pictograph: the sun",
    "mnem": "A round <b>sun</b> squared off, spot in the middle — sun, <b>day</b>."
  },
  {
    "rank": 102,
    "c": "军",
    "py": "jūn",
    "en": "army; military",
    "ex": "他当过军人。",
    "exPy": "tā dāng guò jūn rén.",
    "exEn": "He used to be a soldier.",
    "parts": "冖 cover + 车 chariot",
    "mnem": "<b>Chariots</b> (车) under camouflage <b>cover</b> (冖) — the <b>army</b>."
  },
  {
    "rank": 103,
    "c": "者",
    "py": "zhě",
    "en": "(suffix: one who; or)",
    "ex": "你去或者我去，都行。",
    "exPy": "nǐ qù huò zhě wǒ qù, dōu xíng.",
    "exEn": "Either you go or I go, both are fine.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 者我 is written zhě wǒ but said zhé wǒ.",
    "parts": "耂 old master + 日",
    "mnem": "The old master (耂) who does the thing — the do-<b>er</b>; 或者: this one <b>or</b> that one."
  },
  {
    "rank": 104,
    "c": "意",
    "py": "yì",
    "en": "meaning; idea (in 意思)",
    "ex": "这是什么意思？",
    "exPy": "zhè shì shén me yì si?",
    "exEn": "What does this mean?",
    "parts": "音 sound + 心 heart",
    "mnem": "The <b>sound</b> (音) your <b>heart</b> (心) makes — <b>meaning</b>, idea: 意思."
  },
  {
    "rank": 105,
    "c": "无",
    "py": "wú",
    "en": "without; not (formal, in 无所谓)",
    "ex": "无所谓，随便你。",
    "exPy": "wú suǒ wèi, suí biàn nǐ.",
    "exEn": "Whatever, up to you.",
    "parts": "a dancer's sweeping arms",
    "mnem": "A dancer's arms sweeping over emptiness — <b>nothing</b>, without: 无所谓 nothing worth mentioning, whatever."
  },
  {
    "rank": 106,
    "c": "力",
    "py": "lì",
    "en": "strength; effort (in 努力)",
    "ex": "你要努力！",
    "exPy": "nǐ yào nǔ lì!",
    "exEn": "You need to work hard!",
    "parts": "pictograph: a flexed arm at the plow",
    "mnem": "A flexed <b>arm</b> straining at the plow — <b>strength</b>: 努力 push your strength."
  },
  {
    "rank": 107,
    "c": "它",
    "py": "tā",
    "en": "it",
    "ex": "它是我的猫。",
    "exPy": "tā shì wǒ de māo.",
    "exEn": "It's my cat.",
    "parts": "宀 roof + 匕 (originally a snake)",
    "mnem": "The thing under the <b>roof</b> (宀) that isn't a person — originally a snake: <b>it</b>."
  },
  {
    "rank": 108,
    "c": "与",
    "py": "yǔ",
    "en": "and; with (formal)",
    "ex": "这与我无关。",
    "exPy": "zhè yǔ wǒ wú guān.",
    "exEn": "This has nothing to do with me.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 与我 is written yǔ wǒ but said yú wǒ.",
    "parts": "from 與: hands passing something over",
    "mnem": "Hands passing something across — together <b>with</b>, and: 与我无关 nothing passed to me."
  },
  {
    "rank": 109,
    "c": "长",
    "py": "zhǎng",
    "en": "to grow; long",
    "ex": "你长高了！",
    "exPy": "nǐ zhǎng gāo le!",
    "exEn": "You've grown taller!",
    "parts": "pictograph: long flowing hair",
    "mnem": "<b>Long</b> hair streaming — cháng = long; hair keeps <b>growing</b> — zhǎng = grow.",
    "lesson": {
      "uses": [
        {
          "g": "cháng — long",
          "ex": "这条路好长啊！",
          "exPy": "zhè tiáo lù hǎo cháng a!",
          "exEn": "This road is so long!"
        },
        {
          "g": "zhǎng — to grow (up)",
          "ex": "孩子们长大了。",
          "exPy": "hái zi men zhǎng dà le.",
          "exEn": "The kids have grown up."
        },
        {
          "g": "zhǎng — 长得 describes someone's looks",
          "h": "长得",
          "hPy": "zhǎng de",
          "ex": "你们俩长得真像！",
          "exPy": "nǐ men liǎ zhǎng de zhēn xiàng!",
          "exEn": "You two look so alike!"
        }
      ]
    }
  },
  {
    "rank": 110,
    "c": "把",
    "py": "bǎ",
    "en": "(object-marker); to hold",
    "ex": "把门关上。",
    "exPy": "bǎ mén guān shàng.",
    "exEn": "Close the door.",
    "parts": "扌 hand + 巴 (≈ <b>bā</b>, sound)",
    "mnem": "A <b>hand</b> (扌) gripping the handle — 把 grabs the object and moves it up front: 把门关上.",
    "lesson": {
      "uses": [
        {
          "g": "“take X and …” — focuses on what happens to the object",
          "h": "把 X + verb",
          "hPy": "bǎ X + verb",
          "ex": "请把手机给我。",
          "exPy": "qǐng bǎ shǒu jī gěi wǒ.",
          "exEn": "Please hand me the phone."
        },
        {
          "g": "great for mishaps — what got lost, broken, forgotten",
          "ex": "我把钥匙忘在家里了。",
          "exPy": "wǒ bǎ yào shi wàng zài jiā lǐ le.",
          "exEn": "I left my keys at home."
        },
        {
          "g": "measure word for things with handles",
          "h": "一把",
          "hPy": "yì bǎ",
          "ex": "带一把伞吧。",
          "exPy": "dài yì bǎ sǎn ba.",
          "exEn": "Take an umbrella."
        }
      ],
      "intro": "The famous 把-sentence: pull the object up front and say what you did to it."
    }
  },
  {
    "rank": 111,
    "c": "机",
    "py": "jī",
    "en": "machine (in 手机)",
    "ex": "我手机没电了。",
    "exPy": "wǒ shǒu jī méi diàn le.",
    "exEn": "My phone's out of battery.",
    "parts": "木 wood + 几 (≈ <b>jī</b>, sound)",
    "mnem": "A <b>wooden</b> (木) contraption on a small table (几) — a <b>machine</b>: 手机 = hand-machine, phone."
  },
  {
    "rank": 112,
    "c": "十",
    "py": "shí",
    "en": "ten",
    "ex": "我要十个饺子。",
    "exPy": "wǒ yào shí gè jiǎo zi.",
    "exEn": "I'll have ten dumplings.",
    "parts": "a full cross",
    "mnem": "A complete cross — both directions covered: <b>ten</b>, completeness."
  },
  {
    "rank": 113,
    "c": "民",
    "py": "mín",
    "en": "people; citizens (in 移民)",
    "ex": "移民很不容易。",
    "exPy": "yí mín hěn bù róng yì.",
    "exEn": "Immigrating isn't easy.",
    "parts": "pictograph: an old branding mark",
    "mnem": "The masses marked for service in ancient times — the <b>people</b>: 移民 moving people, immigrants."
  },
  {
    "rank": 114,
    "c": "第",
    "py": "dì",
    "en": "(ordinal prefix)",
    "ex": "这是我第一次来。",
    "exPy": "zhè shì wǒ dì yī cì lái.",
    "exEn": "This is my first time here.",
    "parts": "⺮ bamboo + 弟 (≈ <b>dì</b>, sound)",
    "mnem": "<b>Bamboo</b> (⺮) slips numbered in sequence — the ordinal prefix: 第一 first."
  },
  {
    "rank": 115,
    "c": "公",
    "py": "gōng",
    "en": "public (in 公司)",
    "ex": "我在公司加班。",
    "exPy": "wǒ zài gōng sī jiā bān.",
    "exEn": "I'm working overtime at the office.",
    "parts": "八 divide + 厶 private",
    "mnem": "<b>Dividing</b> (八) up what was <b>private</b> (厶) — <b>public</b>: 公司 the public office, a company."
  },
  {
    "rank": 116,
    "c": "此",
    "py": "cǐ",
    "en": "this (formal, in 因此)",
    "ex": "因此，我们决定取消。",
    "exPy": "yīn cǐ, wǒ men jué dìng qǔ xiāo.",
    "exEn": "So, we decided to cancel.",
    "parts": "止 stop + 匕",
    "mnem": "Your foot <b>stops</b> (止) right here — <b>this</b> (formal): 因此 therefore."
  },
  {
    "rank": 117,
    "c": "已",
    "py": "yǐ",
    "en": "already (in 已经)",
    "ex": "我已经到了。",
    "exPy": "wǒ yǐ jīng dào le.",
    "exEn": "I've already arrived.",
    "parts": "a snake already coiled",
    "mnem": "The snake has <b>already</b> coiled up for the day — done: 已经."
  },
  {
    "rank": 118,
    "c": "工",
    "py": "gōng",
    "en": "work; labor",
    "ex": "这个工作很有意思。",
    "exPy": "zhè ge gōng zuò hěn yǒu yì si.",
    "exEn": "This job is interesting.",
    "parts": "pictograph: a carpenter's square",
    "mnem": "A carpenter's square — <b>work</b>, labor: 工作."
  },
  {
    "rank": 119,
    "c": "使",
    "py": "shǐ",
    "en": "to make; even if (in 即使)",
    "ex": "即使很累，我也要去。",
    "exPy": "jí shǐ hěn lèi, wǒ yě yào qù.",
    "exEn": "Even if I'm tired, I'll still go.",
    "tone": "Tone change: a 3rd tone before another 3rd tone is pronounced 2nd tone — 使很 is written shǐ hěn but said shí hěn.",
    "parts": "亻 person + 吏 official",
    "mnem": "The <b>official</b> (吏) standing over a <b>person</b> (亻), making them act — to make, to <b>cause</b>; 即使 even if."
  },
  {
    "rank": 120,
    "c": "情",
    "py": "qíng",
    "en": "feeling; mood (in 心情)",
    "ex": "你今天心情怎么样？",
    "exPy": "nǐ jīn tiān xīn qíng zěn me yàng?",
    "exEn": "How are you feeling today?",
    "parts": "忄 heart + 青 (≈ <b>qīng</b>, sound)",
    "mnem": "What the young green (青) <b>heart</b> (忄) is full of — <b>feelings</b>: 心情 mood."
  },
  {
    "rank": 121,
    "c": "明",
    "py": "míng",
    "en": "clear; to understand (in 明白)",
    "ex": "我明白了。",
    "exPy": "wǒ míng bái le.",
    "exEn": "I understand now.",
    "parts": "日 sun + 月 moon",
    "mnem": "<b>Sun</b> (日) and <b>moon</b> (月) side by side — the brightest things there are: <b>bright</b>, clear: 明白."
  },
  {
    "rank": 122,
    "c": "性",
    "py": "xìng",
    "en": "nature; character (in 性格)",
    "ex": "他性格很好。",
    "exPy": "tā xìng gé hěn hǎo.",
    "exEn": "He has a good personality.",
    "parts": "忄 heart + 生 born (≈ <b>shēng</b>, sound)",
    "mnem": "The <b>heart</b> (忄) you're <b>born</b> (生) with — your <b>nature</b>: 性格 character."
  },
  {
    "rank": 123,
    "c": "知",
    "py": "zhī",
    "en": "to know (in 知道)",
    "ex": "你知道吗？",
    "exPy": "nǐ zhī dào ma?",
    "exEn": "Do you know?",
    "parts": "矢 arrow + 口 mouth",
    "mnem": "When you <b>know</b>, your words (口) fly straight as <b>arrows</b> (矢) — 知道."
  },
  {
    "rank": 124,
    "c": "全",
    "py": "quán",
    "en": "whole; entire",
    "ex": "我们全都同意。",
    "exPy": "wǒ men quán dōu tóng yì.",
    "exEn": "We all agree.",
    "parts": "人 person + 王 jade",
    "mnem": "A flawless piece of <b>jade</b> (王) held safe in a person's hands — <b>whole</b>, complete: 全都 all of it."
  },
  {
    "rank": 125,
    "c": "三",
    "py": "sān",
    "en": "three",
    "ex": "我们三个人一起去。",
    "exPy": "wǒ men sān gè rén yì qǐ qù.",
    "exEn": "The three of us will go together.",
    "parts": "three strokes",
    "mnem": "Three strokes — <b>three</b>."
  },
  {
    "rank": 126,
    "c": "又",
    "py": "yòu",
    "en": "again; also",
    "ex": "你又迟到了！",
    "exPy": "nǐ yòu chí dào le!",
    "exEn": "You're late again!",
    "parts": "pictograph: a right hand",
    "mnem": "The same right <b>hand</b> reaching out yet <b>again</b> — 又迟到了! late again!",
    "lesson": {
      "uses": [
        {
          "g": "“again” — for things that already happened (future repeats use 再)",
          "ex": "我又忘带钥匙了。",
          "exPy": "wǒ yòu wàng dài yào shi le.",
          "exEn": "I forgot my keys again."
        },
        {
          "g": "“both … and …”",
          "h": "又……又",
          "hPy": "yòu … yòu",
          "ex": "这家店又便宜又好吃。",
          "exPy": "zhè jiā diàn yòu pián yi yòu hǎo chī.",
          "exEn": "This place is cheap and tasty."
        }
      ]
    }
  },
  {
    "rank": 127,
    "c": "关",
    "py": "guān",
    "en": "to close; related (in 没关系)",
    "ex": "没关系。",
    "exPy": "méi guān xì.",
    "exEn": "No worries; it's okay.",
    "parts": "from 關: a bar across a gate",
    "mnem": "The bar dropped across the gate — to <b>close</b>; 没关系: no gate between us, no worries."
  },
  {
    "rank": 128,
    "c": "点",
    "py": "diǎn",
    "en": "o'clock; a bit; dot",
    "ex": "几点了？",
    "exPy": "jǐ diǎn le?",
    "exEn": "What time is it?",
    "parts": "占 (≈ <b>zhàn</b>, sound) + 灬 fire",
    "mnem": "Tiny <b>flames</b> (灬) — <b>dots</b>; the clock's dots give 几点 what o'clock; a dot of something = 一点儿 a bit.",
    "lesson": {
      "uses": [
        {
          "g": "o'clock",
          "ex": "我们六点见。",
          "exPy": "wǒ men liù diǎn jiàn.",
          "exEn": "See you at six."
        },
        {
          "g": "“a bit” — 一点儿 goes after, 有点儿 before (usually complaints)",
          "h": "一点儿 / 有点儿",
          "hPy": "yì diǎnr / yǒu diǎnr",
          "ex": "我有点儿累。",
          "exPy": "wǒ yǒu diǎnr lèi.",
          "exEn": "I'm a bit tired."
        },
        {
          "g": "to order food — “point at” the menu",
          "h": "点菜",
          "hPy": "diǎn cài",
          "ex": "我们点菜吧！",
          "exPy": "wǒ men diǎn cài ba!",
          "exEn": "Let's order!"
        }
      ]
    }
  },
  {
    "rank": 129,
    "c": "正",
    "py": "zhèng",
    "en": "exactly; right now (in 正在)",
    "ex": "我正在吃饭。",
    "exPy": "wǒ zhèng zài chī fàn.",
    "exEn": "I'm eating right now.",
    "parts": "一 line + 止 foot stopping",
    "mnem": "Your foot (止) <b>stops</b> exactly at the line (一) — <b>exactly</b> right: 正在 right in the middle of doing."
  },
  {
    "rank": 130,
    "c": "业",
    "py": "yè",
    "en": "profession (in 作业/毕业)",
    "ex": "你做完作业了吗？",
    "exPy": "nǐ zuò wán zuò yè le ma?",
    "exEn": "Have you finished your homework?",
    "parts": "pictograph: a rack of ceremonial bells",
    "mnem": "The instrument rack you practice at daily — your <b>trade</b>: 作业 homework, 毕业 graduate."
  },
  {
    "rank": 131,
    "c": "外",
    "py": "wài",
    "en": "outside; foreign",
    "ex": "外面在下雨。",
    "exPy": "wài miàn zài xià yǔ.",
    "exEn": "It's raining outside.",
    "parts": "夕 evening + 卜 divination",
    "mnem": "Reading omens (卜) in the <b>evening</b> (夕) was done <b>outside</b> the house — 外面."
  },
  {
    "rank": 132,
    "c": "将",
    "py": "jiāng",
    "en": "will (in 将来)",
    "ex": "我将来想当医生。",
    "exPy": "wǒ jiāng lái xiǎng dāng yī shēng.",
    "exEn": "In the future, I want to be a doctor.",
    "parts": "爿 side + 月 + 寸 hand",
    "mnem": "The general (将军!) plans what his hand (寸) <b>will</b> do next — 将来 the future."
  },
  {
    "rank": 133,
    "c": "两",
    "py": "liǎng",
    "en": "two (measure use)",
    "ex": "我要两杯奶茶。",
    "exPy": "wǒ yào liǎng bēi nǎi chá.",
    "exEn": "I want two milk teas.",
    "parts": "one frame + two figures inside",
    "mnem": "<b>Two</b> people riding in one cart frame — 两个人; the measure-word twin of 二."
  },
  {
    "rank": 134,
    "c": "高",
    "py": "gāo",
    "en": "tall; high",
    "ex": "他很高。",
    "exPy": "tā hěn gāo.",
    "exEn": "He's tall.",
    "parts": "pictograph: a tall watchtower",
    "mnem": "A watchtower with roof upon roof — <b>tall</b>, high."
  },
  {
    "rank": 135,
    "c": "间",
    "py": "jiān",
    "en": "room (in 房间)",
    "ex": "我们的房间在哪儿？",
    "exPy": "wǒ men de fáng jiān zài nǎr?",
    "exEn": "Where's our room?",
    "parts": "门 door + 日 sun",
    "mnem": "<b>Sunlight</b> (日) slipping through the crack of the <b>door</b> (门) — the space <b>between</b>: 房间 a room."
  },
  {
    "rank": 136,
    "c": "由",
    "py": "yóu",
    "en": "due to (in 由于)",
    "ex": "由于堵车，我迟到了。",
    "exPy": "yóu yú dǔ chē, wǒ chí dào le.",
    "exEn": "I was late due to traffic.",
    "parts": "田 field + a sprout poking out",
    "mnem": "A sprout pushing up <b>from</b> the field (田) — from, <b>due to</b>: 由于."
  },
  {
    "rank": 137,
    "c": "问",
    "py": "wèn",
    "en": "to ask",
    "ex": "我可以问你一个问题吗？",
    "exPy": "wǒ kě yǐ wèn nǐ yí gè wèn tí ma?",
    "exEn": "Can I ask you a question?",
    "parts": "门 door (≈ <b>mén</b>, sound) + 口 mouth",
    "mnem": "Put your <b>mouth</b> (口) up to the <b>door</b> (门) and <b>ask</b> a question."
  },
  {
    "rank": 138,
    "c": "很",
    "py": "hěn",
    "en": "very",
    "ex": "今天很热。",
    "exPy": "jīn tiān hěn rè.",
    "exEn": "It's very hot today.",
    "parts": "彳 step + 艮 stubborn",
    "mnem": "A <b>stubborn</b> (艮) determined stride (彳) — emphatically so: <b>very</b>."
  },
  {
    "rank": 139,
    "c": "最",
    "py": "zuì",
    "en": "most; -est",
    "ex": "这是我最喜欢的歌。",
    "exPy": "zhè shì wǒ zuì xǐ huān de gē.",
    "exEn": "This is my favorite song.",
    "parts": "日 sun + 取 take",
    "mnem": "<b>Take</b> (取) the top spot under the <b>sun</b> (日) — the <b>most</b>: 最喜欢 favorite."
  },
  {
    "rank": 140,
    "c": "重",
    "py": "zhòng",
    "en": "heavy; important (in 重要)",
    "ex": "这件事很重要。",
    "exPy": "zhè jiàn shì hěn zhòng yào.",
    "exEn": "This matter is very important.",
    "parts": "a figure carrying a loaded sack",
    "mnem": "Bent under a loaded sack — <b>heavy</b>; and what's heavy, matters: 重要 important."
  }
];
