// Shared data for kana.html and the SRS app (pages/srs/).
// Extracted verbatim from kana.html.
window.KANA_DATA = {};

// ----- Rows -----
window.KANA_DATA.rows = [
  { id: "a",  hira: "あいうえお", kata: "アイウエオ", basic: true },
  { id: "k",  hira: "かきくけこ", kata: "カキクケコ", basic: true },
  { id: "s",  hira: "さしすせそ", kata: "サシスセソ", basic: true },
  { id: "t",  hira: "たちつてと", kata: "タチツテト", basic: true },
  { id: "n",  hira: "なにぬねの", kata: "ナニヌネノ", basic: true },
  { id: "h",  hira: "はひふへほ", kata: "ハヒフヘホ", basic: true },
  { id: "m",  hira: "まみむめも", kata: "マミムメモ", basic: true },
  { id: "y",  hira: "やゆよ",     kata: "ヤユヨ",     basic: true },
  { id: "r",  hira: "らりるれろ", kata: "ラリルレロ", basic: true },
  { id: "w",  hira: "わをん",     kata: "ワヲン",     basic: true },
  { id: "g",  hira: "がぎぐげご", kata: "ガギグゲゴ", basic: false },
  { id: "z",  hira: "ざじずぜぞ", kata: "ザジズゼゾ", basic: false },
  { id: "d",  hira: "だぢづでど", kata: "ダヂヅデド", basic: false },
  { id: "b",  hira: "ばびぶべぼ", kata: "バビブベボ", basic: false },
  { id: "p",  hira: "ぱぴぷぺぽ", kata: "パピプペポ", basic: false },
];

// ----- Kana data -----
// r = romaji, h/k = hiragana/katakana, row = row id,
// wh/wk = example word in each script, wr = word romaji, en = meaning,
// e = cute picture, note = little tip shown on reveal, noteK = katakana-only extra,
// mh/mk = shape mnemonic for the hiragana/katakana glyph (voiced rows reuse the
// basic shapes plus ゛/゜, so they don't carry their own).
window.KANA_DATA.kana = [
  // あ row
  { r: "a",   h: "あ", k: "ア", row: "a", wh: "あり",           wk: "アリ",           wr: "ari",            en: "ant",              e: "🐜",
    mh: "An Apple with a stem and a leaf poking out the top.",
    mk: "An Axe with a bent handle, mid-chop." },
  { r: "i",   h: "い", k: "イ", row: "a", wh: "いちご",         wk: "イチゴ",         wr: "ichigo",         en: "strawberry",       e: "🍓",
    mh: "Two eels swimming side by side — “ii” means eel-eel!",
    mk: "An easel standing on one leg." },
  { r: "u",   h: "う", k: "ウ", row: "a", wh: "うし",           wk: "ウシ",           wr: "ushi",           en: "cow",              e: "🐮",
    mh: "Tip your head — it's a capital “U” lying on its side.",
    mk: "う squared off and given a roof with a little chimney." },
  { r: "e",   h: "え", k: "エ", row: "a", wh: "えんぴつ",       wk: "エンピツ",       wr: "enpitsu",        en: "pencil",           e: "✏️",
    mh: "An Exotic bird strutting along with a curly tail.",
    mk: "An Elevator between two floors (a steel I-beam)." },
  { r: "o",   h: "お", k: "オ", row: "a", wh: "おばけ",         wk: "オバケ",         wr: "obake",          en: "ghost",            e: "👻",
    mh: "あ's big-bellied cousin: a round “O” tummy plus a floating crumb — “oh!”",
    mk: "An Olympic skier slaloming past a signpost." },
  // か row
  { r: "ka",  h: "か", k: "カ", row: "k", wh: "かめ",           wk: "カメ",           wr: "kame",           en: "turtle",           e: "🐢",
    mh: "A mosquito — “ka” is Japanese for mosquito! The dash is its buzzing wing.",
    mk: "The mosquito again — か minus its wing-dash. Freebie!" },
  { r: "ki",  h: "き", k: "キ", row: "k", wh: "きのこ",         wk: "キノコ",         wr: "kinoko",         en: "mushroom",         e: "🍄",
    mh: "A Key — two teeth on top, a little ring at the bottom.",
    mk: "The top half of き — still a Key." },
  { r: "ku",  h: "く", k: "ク", row: "k", wh: "くま",           wk: "クマ",           wr: "kuma",           en: "bear",             e: "🐻",
    mh: "The open beak of a cuckoo — “ku ku!”",
    mk: "く the cuckoo's beak, now wearing a flat cap." },
  { r: "ke",  h: "け", k: "ケ", row: "k", wh: "けーき",         wk: "ケーキ",         wr: "kēki",           en: "cake",             e: "🍰",
    mh: "A Keg with a tap sticking out the side.",
    mk: "A tipped-over letter K — it still opens the Keg.",
    note: "The ー stretches the vowel: “keh-ki”. Cake is a loanword, so it's usually written in katakana: ケーキ." },
  { r: "ko",  h: "こ", k: "コ", row: "k", wh: "こあら",         wk: "コアラ",         wr: "koara",          en: "koala",            e: "🐨",
    mh: "Two little koi fish swimming, one above the other.",
    mk: "A COrner — two walls of a box." },
  // さ row
  { r: "sa",  h: "さ", k: "サ", row: "s", wh: "さかな",         wk: "サカナ",         wr: "sakana",         en: "fish",             e: "🐟",
    mh: "き's little sibling — a key with one bar missing, just for the SAfe.",
    mk: "Two blades of grass poking up through a bar — a fresh SAlad." },
  { r: "shi", h: "し", k: "シ", row: "s", wh: "しかく",         wk: "シカク",         wr: "shikaku",        en: "square",           e: "🟦",
    mh: "A fishing hook on a long line — SHE caught a fish.",
    mk: "SHE's smiling: three splashes lying flat, drawn bottom-up ↗ like a smile.",
    note: "It's “shi”, not “si”!", noteK: "Watch out: シ (shi) vs ツ (tsu) — shi's strokes lie down and are drawn bottom-up, like a smile." },
  { r: "su",  h: "す", k: "ス", row: "s", wh: "すいか",         wk: "スイカ",         wr: "suika",          en: "watermelon",       e: "🍉",
    mh: "A loop-de-loop swing hanging from a bar — SUper fun!",
    mk: "A Ski jump — swoosh down, kick out at the end." },
  { r: "se",  h: "せ", k: "セ", row: "s", wh: "せみ",           wk: "セミ",           wr: "semi",           en: "cicada",           e: "🦗",
    mh: "A wide-open mouth with a fang — it SAYs “se!”",
    mk: "Hiragana せ in a sharper suit — SAme shape, same sound." },
  { r: "so",  h: "そ", k: "ソ", row: "s", wh: "そふとくりーむ", wk: "ソフトクリーム", wr: "sofuto kurīmu",  en: "soft-serve",       e: "🍦",
    mh: "A zigzag stitch — SEW, sew, sew!",
    mk: "One eyebrow above an upright swoosh, drawn top-down ↓ — SO tall.",
    noteK: "Watch out: ソ (so) vs ン (n) — so stands upright and is drawn top-down." },
  // た row
  { r: "ta",  h: "た", k: "タ", row: "t", wh: "たいよう",       wk: "タイヨウ",       wr: "taiyō",          en: "sun",              e: "🌞",
    mh: "Reads as “t + a”: a crossed t on the left, two little strokes for the a.",
    mk: "ク with a dash inside — a TAco with the filling tucked in." },
  { r: "chi", h: "ち", k: "チ", row: "t", wh: "ちょうちょ",     wk: "チョウチョ",     wr: "chōcho",         en: "butterfly",        e: "🦋",
    mh: "さ flipped in a mirror — or a melty number 5. CHEeky!",
    mk: "A flag waving on a bent pole — CHEer!",
    note: "It's “chi”, not “ti”! And spot the small ょ — it blends: chi + yo → “cho”." },
  { r: "tsu", h: "つ", k: "ツ", row: "t", wh: "つき",           wk: "ツキ",           wr: "tsuki",          en: "moon",             e: "🌙",
    mh: "A TSUnami wave rolling in.",
    mk: "TSUnami! Two raindrops and a tall wave — strokes stand up, drawn top-down ↓.",
    note: "It's “tsu”, not “tu”! Its tiny twin っ is silent and doubles the next consonant — see Tips.",
    noteK: "Watch out: ツ (tsu) vs シ (shi) — tsu's strokes stand up and are drawn top-down." },
  { r: "te",  h: "て", k: "テ", row: "t", wh: "てがみ",         wk: "テガミ",         wr: "tegami",         en: "letter",           e: "💌",
    mh: "A TElephone pole with its wire sagging down.",
    mk: "A TElephone pole too: two crossbars and one long leg." },
  { r: "to",  h: "と", k: "ト", row: "t", wh: "とり",           wk: "トリ",           wr: "tori",           en: "bird",             e: "🐥",
    mh: "A TOe with a splinter sticking in it — ouch!",
    mk: "A TOtem pole with one little branch." },
  // な row
  { r: "na",  h: "な", k: "ナ", row: "n", wh: "ながぐつ",       wk: "ナガグツ",       wr: "nagagutsu",      en: "rain boots",       e: "👢",
    mh: "A cross in the sky, a little knot on the ground — NAil that knot down.",
    mk: "A plus sign whose leg got swept sideways — NArrowly slipped on a banana peel." },
  { r: "ni",  h: "に", k: "ニ", row: "n", wh: "にじ",           wk: "ニジ",           wr: "niji",           en: "rainbow",          e: "🌈",
    mh: "A knee! The tall stroke is the leg, the two dashes the kneecap — “ni” = knee.",
    mk: "Literally the kanji 二, “two” — which is read NI!" },
  { r: "nu",  h: "ぬ", k: "ヌ", row: "n", wh: "ぬりえ",         wk: "ヌリエ",         wr: "nurie",          en: "coloring book",    e: "🖍️",
    mh: "NOOdles! Two chopsticks twirling, with a noodle loop caught on the tail.",
    mk: "ク with a chopstick stuck through it — NOOdles snagged again.",
    note: "ぬ has a little loop at the end — め doesn't. Think noodles caught on the tail!" },
  { r: "ne",  h: "ね", k: "ネ", row: "n", wh: "ねこ",           wk: "ネコ",           wr: "neko",           en: "cat",              e: "🐱",
    mh: "A cat! ね starts NEko — see the tail curled up at the bottom.",
    mk: "A scarecrow wearing a NEcktie.",
    note: "ね(ko) has a curled tail — like a cat! れ flicks out, わ curves back in." },
  { r: "no",  h: "の", k: "ノ", row: "n", wh: "のはら",         wk: "ノハラ",         wr: "nohara",         en: "flower field",     e: "🌼",
    mh: "A “no entry” sign — one big swoosh through a circle: NO!",
    mk: "One long slash — NO more, no less. (A looong nose.)" },
  // は row
  { r: "ha",  h: "は", k: "ハ", row: "h", wh: "はぶらし",       wk: "ハブラシ",       wr: "haburashi",      en: "toothbrush",       e: "🪥",
    mh: "A capital H with a small a squeezed in — “Ha!” The loop is the chuckle.",
    mk: "The kanji 八 (eight) — a pair of HAppy eyebrows.",
    note: "As the topic particle it's read “wa” — こんにちは = konnichiwa!" },
  { r: "hi",  h: "ひ", k: "ヒ", row: "h", wh: "ひつじ",         wk: "ヒツジ",         wr: "hitsuji",        en: "sheep",            e: "🐑",
    mh: "A big grin — “hee hee!”",
    mk: "A hockey stick HItting the puck." },
  { r: "fu",  h: "ふ", k: "フ", row: "h", wh: "ふくろう",       wk: "フクロウ",       wr: "fukurō",         en: "owl",              e: "🦉",
    mh: "Mt. FUji with puffs of cloud floating around the peak.",
    mk: "Just a cap's brim — puff air under it: “fu!”",
    note: "“fu” sits halfway between f and h — blow softly, like fogging a mirror." },
  { r: "he",  h: "へ", k: "ヘ", row: "h", wh: "へび",           wk: "ヘビ",           wr: "hebi",           en: "snake",            e: "🐍",
    mh: "A gentle hill — say “heh” as you hike over it.",
    mk: "The same hill! Identical in both scripts — total freebie.",
    note: "As the direction particle it's read “e”. Bonus: へ and ヘ look almost identical in both scripts — one freebie!" },
  { r: "ho",  h: "ほ", k: "ホ", row: "h", wh: "ほうき",         wk: "ホウキ",         wr: "hōki",           en: "broom",            e: "🧹",
    mh: "は wearing a hat — every HOme needs a roof.",
    mk: "A tree (kanji 木) with two baubles dropping off — ho ho HOlly!",
    note: "ほうき: the う stretches the “o” — hōki." },
  // ま row
  { r: "ma",  h: "ま", k: "マ", row: "m", wh: "まど",           wk: "マド",           wr: "mado",           en: "window",           e: "🪟",
    mh: "MAma with her hair in a bun — the loop at the bottom is the bun.",
    mk: "A paper plane nose-diving — MAyday!" },
  { r: "mi",  h: "み", k: "ミ", row: "m", wh: "みず",           wk: "ミズ",           wr: "mizu",           en: "water",            e: "💧",
    mh: "The number 21 in scribbly writing — just turned 21? Lucky ME!",
    mk: "Three tilted dashes — “mi” is three in Japanese (mittsu)!" },
  { r: "mu",  h: "む", k: "ム", row: "m", wh: "むしめがね",     wk: "ムシメガネ",     wr: "mushimegane",    en: "magnifying glass", e: "🔍",
    mh: "A cow saying MOO — round nose-ring in the middle, a fly (the dot) buzzing by.",
    mk: "A folded arm flexing a MUscle." },
  { r: "me",  h: "め", k: "メ", row: "m", wh: "めがね",         wk: "メガネ",         wr: "megane",         en: "glasses",          e: "👓",
    mh: "An eye! め means “eye” — a swirly eye with no loop at the end (the loop is ぬ's).",
    mk: "An X — “X marks the spot… for ME!”" },
  { r: "mo",  h: "も", k: "モ", row: "m", wh: "もも",           wk: "モモ",           wr: "momo",           en: "peach",            e: "🍑",
    mh: "A fishhook with two wiggly worms on it — catch MOre!",
    mk: "Hiragana も gone angular — same fishhook, MOdern style." },
  // や row
  { r: "ya",  h: "や", k: "ヤ", row: "y", wh: "やきゅう",       wk: "ヤキュウ",       wr: "yakyū",          en: "baseball",         e: "⚾",
    mh: "A YAk's face — one horn up, one ear sticking out.",
    mk: "や slimmed down — the YAk lost an ear.",
    note: "Spot the small ゅ: ki + yu → “kyu”, then う stretches it — yakyū." },
  { r: "yu",  h: "ゆ", k: "ユ", row: "y", wh: "ゆきだるま",     wk: "ユキダルマ",     wr: "yukidaruma",     en: "snowman",          e: "⛄",
    mh: "A fish curled around a skewer — YUm!",
    mk: "A squared-off U with a shelf on top — the “U” in YU." },
  { r: "yo",  h: "よ", k: "ヨ", row: "y", wh: "よっと",         wk: "ヨット",         wr: "yotto",          en: "yacht",            e: "⛵",
    mh: "A YO-yo dangling from a finger — flag on top, loop below.",
    mk: "A capital E in the mirror — YO, backwards!",
    note: "Spot the small っ — it doubles the t: yo-t-to. See Tips!" },
  // ら row
  { r: "ra",  h: "ら", k: "ラ", row: "r", wh: "らいおん",       wk: "ライオン",       wr: "raion",          en: "lion",             e: "🦁",
    mh: "A cobRA rearing up, a pebble floating above its head.",
    mk: "フ with a sun visor on top — blocking the RAys." },
  { r: "ri",  h: "り", k: "リ", row: "r", wh: "りす",           wk: "リス",           wr: "risu",           en: "squirrel",         e: "🐿️",
    mh: "Two banks of a RIver — the right bank runs longer.",
    mk: "Nearly identical to hiragana り — the RIver again. Freebie!" },
  { r: "ru",  h: "る", k: "ル", row: "r", wh: "るびー",         wk: "ルビー",         wr: "rubī",           en: "ruby",             e: "💎",
    mh: "A number 3 with a loop on the tail — a RUby ring caught there.",
    mk: "Two legs RUnning — the right one kicks out.",
    note: "る has a little loop at the end, ろ doesn't — “ru has a curl”." },
  { r: "re",  h: "れ", k: "レ", row: "r", wh: "れもん",         wk: "レモン",         wr: "remon",          en: "lemon",            e: "🍋",
    mh: "A RElay runner mid-stride — the tail kicks out (ね's curls in).",
    mk: "A big check mark — “REady? Check!”" },
  { r: "ro",  h: "ろ", k: "ロ", row: "r", wh: "ろうそく",       wk: "ロウソク",       wr: "rōsoku",         en: "candle",           e: "🕯️",
    mh: "A plain number 3 — a winding ROad with no ring at the end (that's る).",
    mk: "A square RObot mouth." },
  // わ row + ん
  { r: "wa",  h: "わ", k: "ワ", row: "w", wh: "わに",           wk: "ワニ",           wr: "wani",           en: "crocodile",        e: "🐊",
    mh: "ね's cousin: the tail swings in toward a round tummy — “WAh!”",
    mk: "An upside-down teacup — the WAter poured out." },
  { r: "o (wo)", h: "を", k: "ヲ", row: "w", wh: "てをふる",    wk: "テヲフル",       wr: "te o furu",      en: "to wave a hand",   e: "👋",
    mh: "Whoa! A gymnast mid-cartwheel — arms out, one leg swinging through.",
    mk: "フ with a bar through it — the rarest kana, you WOn't see it much.",
    note: "を appears almost only as the object particle, pronounced plain “o”: ほんをよむ — I read a book." },
  { r: "n",   h: "ん", k: "ン", row: "w", wh: "ほん",           wk: "ホン",           wr: "hon",            en: "book",             e: "📖",
    mh: "A speedy cursive “n” — one stroke, done!",
    mk: "One dash and a long smile drawn bottom-up ↗ — wink and you're done.",
    note: "The only kana with no vowel — a syllable all by itself: ho-n.",
    noteK: "Watch out: ン (n) vs ソ (so) — n lies flat and is drawn bottom-up." },
  // が row
  { r: "ga",  h: "が", k: "ガ", row: "g", wh: "がっこう",       wk: "ガッコウ",       wr: "gakkō",          en: "school",           e: "🏫",
    note: "か + ゛ = ga. And spot the small っ doubling the k: ga-k-kō!" },
  { r: "gi",  h: "ぎ", k: "ギ", row: "g", wh: "ぎんこう",       wk: "ギンコウ",       wr: "ginkō",          en: "bank",             e: "🏦" },
  { r: "gu",  h: "ぐ", k: "グ", row: "g", wh: "ぐみ",           wk: "グミ",           wr: "gumi",           en: "gummy candy",      e: "🍬" },
  { r: "ge",  h: "げ", k: "ゲ", row: "g", wh: "げた",           wk: "ゲタ",           wr: "geta",           en: "wooden sandals",   e: "🩴" },
  { r: "go",  h: "ご", k: "ゴ", row: "g", wh: "ごはん",         wk: "ゴハン",         wr: "gohan",          en: "rice, a meal",     e: "🍚" },
  // ざ row
  { r: "za",  h: "ざ", k: "ザ", row: "z", wh: "ざっし",         wk: "ザッシ",         wr: "zasshi",         en: "magazine",         e: "📰",
    note: "さ + ゛ = za. Small っ again: za-s-shi." },
  { r: "ji",  h: "じ", k: "ジ", row: "z", wh: "じてんしゃ",     wk: "ジテンシャ",     wr: "jitensha",       en: "bicycle",          e: "🚲",
    note: "し + ゛ = ji. Spot the small ゃ: shi + ya → “sha”." },
  { r: "zu",  h: "ず", k: "ズ", row: "z", wh: "ずぼん",         wk: "ズボン",         wr: "zubon",          en: "trousers",         e: "👖" },
  { r: "ze",  h: "ぜ", k: "ゼ", row: "z", wh: "ぜろ",           wk: "ゼロ",           wr: "zero",           en: "zero",             e: "0️⃣" },
  { r: "zo",  h: "ぞ", k: "ゾ", row: "z", wh: "ぞう",           wk: "ゾウ",           wr: "zō",             en: "elephant",         e: "🐘" },
  // だ row
  { r: "da",  h: "だ", k: "ダ", row: "d", wh: "だんご",         wk: "ダンゴ",         wr: "dango",          en: "sweet dumplings",  e: "🍡",
    note: "た + ゛ = da — the two dots (dakuten) voice t into d." },
  { r: "ji (dji)", h: "ぢ", k: "ヂ", row: "d", wh: "はなぢ",    wk: "ハナヂ",         wr: "hanaji",         en: "nosebleed",        e: "🤧",
    note: "Rare! Sounds exactly like じ. It only shows up in a few words like はなぢ (hana + chi)." },
  { r: "zu (dzu)", h: "づ", k: "ヅ", row: "d", wh: "みかづき",  wk: "ミカヅキ",       wr: "mikazuki",       en: "crescent moon",    e: "🌛",
    note: "Rare! Sounds exactly like ず. You'll mostly meet it in compounds like みかづき (mika + tsuki)." },
  { r: "de",  h: "で", k: "デ", row: "d", wh: "でんわ",         wk: "デンワ",         wr: "denwa",          en: "telephone",        e: "☎️" },
  { r: "do",  h: "ど", k: "ド", row: "d", wh: "どーなつ",       wk: "ドーナツ",       wr: "dōnatsu",        en: "donut",            e: "🍩" },
  // ば row
  { r: "ba",  h: "ば", k: "バ", row: "b", wh: "ばなな",         wk: "バナナ",         wr: "banana",         en: "banana",           e: "🍌",
    note: "は + ゛ = ba — the same two dots turn h into b." },
  { r: "bi",  h: "び", k: "ビ", row: "b", wh: "びっくり",       wk: "ビックリ",       wr: "bikkuri",        en: "surprise!",        e: "😲",
    note: "Small っ doubles the k: bi-k-kuri!" },
  { r: "bu",  h: "ぶ", k: "ブ", row: "b", wh: "ぶた",           wk: "ブタ",           wr: "buta",           en: "pig",              e: "🐷" },
  { r: "be",  h: "べ", k: "ベ", row: "b", wh: "べんとう",       wk: "ベントウ",       wr: "bentō",          en: "lunch box",        e: "🍱" },
  { r: "bo",  h: "ぼ", k: "ボ", row: "b", wh: "ぼうし",         wk: "ボウシ",         wr: "bōshi",          en: "hat",              e: "👒" },
  // ぱ row
  { r: "pa",  h: "ぱ", k: "パ", row: "p", wh: "ぱんだ",         wk: "パンダ",         wr: "panda",          en: "panda",            e: "🐼",
    note: "は + ゜ = pa. The little circle means “p”!" },
  { r: "pi",  h: "ぴ", k: "ピ", row: "p", wh: "ぴあの",         wk: "ピアノ",         wr: "piano",          en: "piano",            e: "🎹" },
  { r: "pu",  h: "ぷ", k: "プ", row: "p", wh: "ぷりん",         wk: "プリン",         wr: "purin",          en: "pudding",          e: "🍮" },
  { r: "pe",  h: "ぺ", k: "ペ", row: "p", wh: "ぺんぎん",       wk: "ペンギン",       wr: "pengin",         en: "penguin",          e: "🐧" },
  { r: "po",  h: "ぽ", k: "ポ", row: "p", wh: "ぽすと",         wk: "ポスト",         wr: "posuto",         en: "postbox",          e: "📮" },
];
