// Shared data for radicals.html and the SRS app (pages/srs/).
// Extracted verbatim from radicals.html.
// ----- Data: the 40 radicals -----
window.RADICALS_DATA = [
  { n: 1,  base: "人", variant: "亻", pinyin: "rén",  english: "person",            examples: "今，他" },
  { n: 2,  base: "刀", variant: "刂", pinyin: "dāo",  english: "knife",             examples: "分，到" },
  { n: 3,  base: "力", variant: "",   pinyin: "lì",   english: "power",             examples: "加，助" },
  { n: 4,  base: "又", variant: "",   pinyin: "yòu",  english: "right hand, again", examples: "友，取" },
  { n: 5,  base: "口", variant: "",   pinyin: "kǒu",  english: "mouth",             examples: "叫，可" },
  { n: 6,  base: "囗", variant: "",   pinyin: "wéi",  english: "enclose",           examples: "回，因" },
  { n: 7,  base: "土", variant: "",   pinyin: "tǔ",   english: "earth",             examples: "在，坐" },
  { n: 8,  base: "夕", variant: "",   pinyin: "xī",   english: "sunset",            examples: "外，多" },
  { n: 9,  base: "大", variant: "",   pinyin: "dà",   english: "big",               examples: "天，太" },
  { n: 10, base: "女", variant: "",   pinyin: "nǚ",   english: "woman",             examples: "婆，好" },
  { n: 11, base: "子", variant: "",   pinyin: "zǐ",   english: "child",             examples: "字，孩" },
  { n: 12, base: "寸", variant: "",   pinyin: "cùn",  english: "inch",              examples: "寺，封" },
  { n: 13, base: "小", variant: "",   pinyin: "xiǎo", english: "small",             examples: "少，尖" },
  { n: 14, base: "工", variant: "",   pinyin: "gōng", english: "labor, work",       examples: "左，差" },
  { n: 15, base: "幺", variant: "",   pinyin: "yāo",  english: "tiny, small",       examples: "幻，幼" },
  { n: 16, base: "弓", variant: "",   pinyin: "gōng", english: "bow",               examples: "引，弟" },
  { n: 17, base: "心", variant: "忄", pinyin: "xīn",  english: "heart",             examples: "想，忙" },
  { n: 18, base: "戈", variant: "",   pinyin: "gē",   english: "dagger-axe",        examples: "我，或" },
  { n: 19, base: "手", variant: "扌", pinyin: "shǒu", english: "hand",              examples: "拿，打" },
  { n: 20, base: "日", variant: "",   pinyin: "rì",   english: "sun",               examples: "早，明" },
  { n: 21, base: "月", variant: "",   pinyin: "yuè",  english: "moon",              examples: "期，朗" },
  { n: 22, base: "木", variant: "",   pinyin: "mù",   english: "wood",              examples: "李，杯" },
  { n: 23, base: "水", variant: "氵", pinyin: "shuǐ", english: "water",             examples: "汞，洗" },
  { n: 24, base: "火", variant: "灬", pinyin: "huǒ",  english: "fire",              examples: "烧，热" },
  { n: 25, base: "田", variant: "",   pinyin: "tián", english: "field",             examples: "男，留" },
  { n: 26, base: "目", variant: "",   pinyin: "mù",   english: "eye",               examples: "看，睡" },
  { n: 27, base: "示", variant: "礻", pinyin: "shì",  english: "show",              examples: "票，社" },
  { n: 28, base: "糸", variant: "纟", pinyin: "mì",   english: "fine silk",         examples: "素，红" },
  { n: 29, base: "耳", variant: "",   pinyin: "ěr",   english: "ear",               examples: "聋，聊" },
  { n: 30, base: "衣", variant: "衤", pinyin: "yī",   english: "clothing",          examples: "袋，衫" },
  { n: 31, base: "言", variant: "讠", pinyin: "yán",  english: "speech",            examples: "誓，话" },
  { n: 32, base: "贝", variant: "",   pinyin: "bèi",  english: "cowrie shell",      examples: "贵，财" },
  { n: 33, base: "走", variant: "",   pinyin: "zǒu",  english: "walk",              examples: "趣，起" },
  { n: 34, base: "足", variant: "",   pinyin: "zú",   english: "foot",              examples: "跳，跑" },
  { n: 35, base: "金", variant: "钅", pinyin: "jīn",  english: "gold",              examples: "鉴，银" },
  { n: 36, base: "门", variant: "",   pinyin: "mén",  english: "door",              examples: "间，闷" },
  { n: 37, base: "隹", variant: "",   pinyin: "zhuī", english: "short-tailed bird", examples: "难，集" },
  { n: 38, base: "雨", variant: "",   pinyin: "yǔ",   english: "rain",              examples: "雪，雷" },
  { n: 39, base: "食", variant: "饣", pinyin: "shí",  english: "eat",               examples: "餐，饭" },
  { n: 40, base: "马", variant: "",   pinyin: "mǎ",   english: "horse",             examples: "骑，骂" },
];
