// Shared data for usage.html and the SRS app (pages/srs/).
// Extracted verbatim from usage.html.
window.USAGE_DATA = {};

// ----- Drill sets: each has a rule shown after every answer -----
window.USAGE_DATA.sets = [
  { id: "NI_NIN", title: "你 vs 您 — plain vs polite “you”",
    rule: "您 nín is the polite form of 你 nǐ — use it for teachers, bosses, elders and respected strangers; use 你 with friends, family and peers. The polite way to ask a surname is 您贵姓? — the casual way is 你姓什么?" },
  { id: "JI_DUOSHAO", title: "几 vs 多少 — asking “how many”",
    rule: "几 jǐ expects a small answer (under 10) and must be followed by a measure word: 几个人? 多少 duōshao works for any number and the measure word is optional: 多少人? or 多少个人?" },
  { id: "KOU_GE", title: "口 vs 个 — counting people",
    rule: "Counting people with 口 kǒu implies they belong to one family — mouths at one table: 我家有五口人. For people in general use 个: 三个人, 二十个学生." },
  { id: "ZHE_NA", title: "zhè/nà vs zhèi/nèi — textbook vs street",
    rule: "In relaxed speech, 这 before a measure word is usually said zhèi and 那 is nèi: zhèi ge, nèi ge. The dictionary readings zhè / nà are for careful or formal speech — and they're what textbooks print." },
  { id: "ADV", title: "Adverb placement — 都 / 也 before the verb",
    rule: "Adverbs like 都 dōu (all, both) and 也 yě (also) come directly before the verb, never after it: 我们都是学生, 我也是工程师." },
  { id: "YI_TONE", title: "一 tone changes",
    rule: "一 is 1st tone (yī) when counting and in ordinals and dates: 一二三, 第一, 一月. Before a 4th tone it becomes 2nd tone: yí ge. Before a 1st, 2nd or 3rd tone it becomes 4th tone: yì zhāng, yì píng, yì qǐ." },
  { id: "NA_NA", title: "那 vs 哪 — that vs which",
    rule: "那 nà points: “that” — 那个人 that person. 哪 nǎ asks: “which?” — 哪个人? Only the tone differs (nà 4th, nǎ 3rd), and in relaxed speech they become nèi and něi. If it's a question, it's 哪." },
  { id: "HAISHI_HUOZHE", title: "还是 vs 或者 — the two “or”s",
    rule: "还是 háishì is “or” only in questions that ask someone to choose: 你喝茶还是喝咖啡? 或(者) huòzhě is “or” only in statements: 咖啡或者茶都可以. Never use 还是 in a statement." },
  { id: "GUO_BIRTHDAY", title: "过生日 — asking about birthdays",
    rule: "The native way to ask is 你什么时候过生日? — “when do you celebrate (过, to pass) your birthday?” The textbook 你的生日是什么时候 is understood but sounds stiff. Answer with the same pattern: 我 + time + 过生日. And remember: 什么时候 asks “when?”, while ……的时候 is the non-question “when …” — 我五岁的时候." },
  { id: "WEEK", title: "上个 / 这个 / 下个 / 每个 — which Wednesday?",
    rule: "Weeks stack like a calendar read downward: 上个星期三 last Wednesday (上 = the one above), 这个星期三 this Wednesday, 下个星期三 next Wednesday (下 = the one below), 每个星期三 every Wednesday — and 每 likes a backing 都 before the verb." },
  { id: "ORDER", title: "Word order — time · who · where · verb",
    rule: "Subject + time + 和/跟 who + 在 where + adverb + verb + object: 我今天和我妈妈在家一起看电视 — “Today I'm watching TV at home together with my mom.” Everything about when, with whom and where comes BEFORE the verb." },
  { id: "TIME_DATE", title: "Times & dates — big to small",
    rule: "Dates run from big to small: year → month → day (2026年7月15日), and the part of day comes before the hour: 下午两点零五 = 2:05 pm. After 点 the minutes need at least two syllables — 2:05 is 两点零五 (líng wǔ), never 两点五. Textbook 刻 (quarter hour) is rarely said — natives prefer 十五分 / 四十五分." },
];

// ----- Drill items -----
// set = SETS id; frame = English context (optional); q = prompt, ___ is the blank;
// opts = choices; a = index of the correct one; zh/py/en = full answer to show & speak.
window.USAGE_DATA.items = [
  // --- 你 vs 您 ---
  { set: "NI_NIN", frame: "Speaking to your teacher…", q: "___ 好！", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "您好！", py: "nín hǎo!", en: "Hello! (polite)",
    why: "Teachers get the respectful 您." },
  { set: "NI_NIN", frame: "Asking your boss's surname…", q: "___ 贵姓？", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "您贵姓？", py: "nín guì xìng?", en: "What is your (honorable) surname?",
    why: "贵姓 is honorific — it pairs with 您, never with plain 你." },
  { set: "NI_NIN", frame: "Chatting with a classmate…", q: "___ 叫什么名字？", opts: ["你 nǐ", "您 nín"], a: 0,
    zh: "你叫什么名字？", py: "nǐ jiào shén me míng zi?", en: "What's your name?",
    why: "Peers get plain 你 — 您 would sound stiff between classmates." },
  { set: "NI_NIN", frame: "Which is the polite way to ask a surname?", q: "", opts: ["您贵姓？", "你姓什么？"], a: 0,
    zh: "您贵姓？", py: "nín guì xìng?", en: "What is your (honorable) surname?",
    why: "您贵姓 is the formal formula; 你姓什么 is the everyday version." },
  { set: "NI_NIN", frame: "Asking an elderly stranger…", q: "请问，___ 是王老师吗？", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "请问，您是王老师吗？", py: "qǐng wèn, nín shì wáng lǎo shī ma?", en: "Excuse me, are you Teacher Wang?",
    why: "Elders and strangers you respect get 您." },
  { set: "NI_NIN", frame: "Texting a good friend…", q: "___ 好吗？", opts: ["你 nǐ", "您 nín"], a: 0,
    zh: "你好吗？", py: "nǐ hǎo ma?", en: "How are you?",
    why: "Friends get 你 — no ceremony needed." },

  // --- 几 vs 多少 ---
  { set: "JI_DUOSHAO", frame: "Families are small…", q: "你家有 ___ 口人？", opts: ["几 jǐ", "多少 duōshao"], a: 0,
    zh: "你家有几口人？", py: "nǐ jiā yǒu jǐ kǒu rén?", en: "How many people are in your family?",
    why: "A family is fewer than ten people, and the measure word 口 follows — classic 几." },
  { set: "JI_DUOSHAO", frame: "A university has thousands of students…", q: "你们大学有 ___ 学生？", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "你们大学有多少学生？", py: "nǐ men dà xué yǒu duō shao xué shēng?", en: "How many students does your university have?",
    why: "A big number — too big for 几. And notice 多少 goes straight to the noun, no measure word needed." },
  { set: "JI_DUOSHAO", frame: "Which is correct?", q: "", opts: ["几人？", "几个人？"], a: 1,
    zh: "几个人？", py: "jǐ ge rén?", en: "How many people?",
    why: "几 must be followed by a measure word — 几个人, never bare 几人." },
  { set: "JI_DUOSHAO", frame: "Which one can drop the measure word?", q: "", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "多少人？", py: "duō shao rén?", en: "How many people?",
    why: "多少人 and 多少个人 are both fine; 几 always keeps its measure word." },
  { set: "JI_DUOSHAO", frame: "Asking the time…", q: "现在 ___ 点？", opts: ["几 jǐ", "多少 duōshao"], a: 0,
    zh: "现在几点？", py: "xiàn zài jǐ diǎn?", en: "What time is it now?",
    why: "Clock hours run 1–12 — a small number, so it's 几点." },
  { set: "JI_DUOSHAO", frame: "Asking the price of a phone…", q: "这个手机 ___ 钱？", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "这个手机多少钱？", py: "zhè ge shǒu jī duō shao qián?", en: "How much is this phone?",
    why: "Prices can be any size — 多少钱 is the fixed way to ask “how much.”" },

  // --- 口 vs 个 ---
  { set: "KOU_GE", frame: "Talking about my family…", q: "我家有五 ___ 人。", opts: ["口 kǒu", "个 gè"], a: 0,
    zh: "我家有五口人。", py: "wǒ jiā yǒu wǔ kǒu rén.", en: "There are five people in my family.",
    why: "Family members are counted with 口 — mouths at one table." },
  { set: "KOU_GE", frame: "Talking about my class…", q: "我们班有二十 ___ 学生。", opts: ["口 kǒu", "个 gè"], a: 1,
    zh: "我们班有二十个学生。", py: "wǒ men bān yǒu èr shí ge xué shēng.", en: "There are twenty students in our class.",
    why: "Classmates aren't one family — plain 个." },
  { set: "KOU_GE", frame: "Asking about their family…", q: "他们家有几 ___ 人？", opts: ["口 kǒu", "个 gè"], a: 0,
    zh: "他们家有几口人？", py: "tā men jiā yǒu jǐ kǒu rén?", en: "How many people are in their family?",
    why: "Asking about a household, so 口." },
  { set: "KOU_GE", frame: "Three strangers over there…", q: "那儿有三 ___ 人。", opts: ["口 kǒu", "个 gè"], a: 1,
    zh: "那儿有三个人。", py: "nàr yǒu sān ge rén.", en: "There are three people over there.",
    why: "Random people get 个 — 口 would claim they're one household." },

  // --- zhè/nà vs zhèi/nèi ---
  { set: "ZHE_NA", frame: "Chatting with friends, 这个 usually sounds like…", q: "", opts: ["zhè ge", "zhèi ge"], a: 1,
    zh: "这个", py: "zhèi ge (colloquial)", en: "this one",
    why: "Real-life casual speech favors zhèi before a measure word." },
  { set: "ZHE_NA", frame: "Reading the news aloud, 那个 is read…", q: "", opts: ["nà ge", "nèi ge"], a: 0,
    zh: "那个", py: "nà ge (formal)", en: "that one",
    why: "Careful, formal speech keeps the dictionary reading nà." },
  { set: "ZHE_NA", frame: "Street Mandarin: 那个人 sounds like…", q: "", opts: ["nà ge rén", "nèi ge rén"], a: 1,
    zh: "那个人", py: "nèi ge rén (colloquial)", en: "that person",
    why: "nèi is the everyday spoken form of 那 before a measure word." },
  { set: "ZHE_NA", frame: "Which reading do textbooks print for 这?", q: "", opts: ["zhè", "zhèi"], a: 0,
    zh: "这", py: "zhè (standard)", en: "this",
    why: "zhè is the standard reading; zhèi is the colloquial variant you'll hear on the street." },

  // --- adverb before the verb ---
  { set: "ADV", frame: "“We are all students.”", q: "", opts: ["我们都是学生。", "我们是都学生。"], a: 0,
    zh: "我们都是学生。", py: "wǒ men dōu shì xué shēng.", en: "We are all students.",
    why: "都 sits right before the verb 是." },
  { set: "ADV", frame: "“I am also an engineer.”", q: "", opts: ["我是也工程师。", "我也是工程师。"], a: 1,
    zh: "我也是工程师。", py: "wǒ yě shì gōng chéng shī.", en: "I am also an engineer.",
    why: "也 goes before the verb 是, never after it." },
  { set: "ADV", frame: "“Mom and dad are both teachers.”", q: "", opts: ["爸爸妈妈都是老师。", "爸爸妈妈是都老师。"], a: 0,
    zh: "爸爸妈妈都是老师。", py: "bà ba mā ma dōu shì lǎo shī.", en: "Mom and dad are both teachers.",
    why: "都 before 是. Bonus: 爸爸妈妈 together is the everyday word for “parents.”" },
  { set: "ADV", frame: "“They are all my friends.”", q: "", opts: ["他们是我的都朋友。", "他们都是我的朋友。"], a: 1,
    zh: "他们都是我的朋友。", py: "tā men dōu shì wǒ de péng you.", en: "They are all my friends.",
    why: "都 attaches to the verb, not to the noun." },

  // --- 一 tone changes ---
  { set: "YI_TONE", frame: "一 + 个 gè (4th tone)", q: "一个 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 1,
    zh: "一个", py: "yí ge", en: "one (of something)",
    why: "Before a 4th tone, 一 becomes 2nd tone: yí ge." },
  { set: "YI_TONE", frame: "一 + 张 zhāng (1st tone)", q: "一张 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一张", py: "yì zhāng", en: "a sheet of",
    why: "Before a 1st tone, 一 becomes 4th tone: yì zhāng." },
  { set: "YI_TONE", frame: "一 + 瓶 píng (2nd tone)", q: "一瓶 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一瓶", py: "yì píng", en: "a bottle of",
    why: "Before a 2nd tone, 一 becomes 4th tone: yì píng." },
  { set: "YI_TONE", frame: "一 + 起 qǐ (3rd tone)", q: "一起 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一起", py: "yì qǐ", en: "together",
    why: "Before a 3rd tone, 一 becomes 4th tone: yì qǐ." },
  { set: "YI_TONE", frame: "Counting: 一，二，三", q: "How is 一 said when counting?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "一，二，三", py: "yī, èr, sān", en: "one, two, three",
    why: "Counting keeps the citation reading: 1st tone yī." },
  { set: "YI_TONE", frame: "Ordinal: 第一", q: "第一 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "第一", py: "dì yī", en: "first",
    why: "Ordinals keep 一 in 1st tone: dì yī." },
  { set: "YI_TONE", frame: "Date: 一月", q: "一月 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "一月", py: "yī yuè", en: "January",
    why: "Dates and month names keep 一 in 1st tone: yī yuè." },
  { set: "YI_TONE", frame: "一 + 杯 bēi (1st tone)", q: "一杯 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一杯", py: "yì bēi", en: "a cup of",
    why: "Before a 1st tone, 一 becomes 4th tone: yì bēi." },
  { set: "YI_TONE", frame: "一 + 年 nián (2nd tone)", q: "一年 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一年", py: "yì nián", en: "one year",
    why: "Before a 2nd tone, 一 becomes 4th tone: yì nián." },
  { set: "YI_TONE", frame: "一 + 点 diǎn (3rd tone)", q: "一点 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一点", py: "yì diǎn", en: "one o'clock; a little",
    why: "Before a 3rd tone, 一 becomes 4th tone: yì diǎn." },
  { set: "YI_TONE", frame: "一 + 样 yàng (4th tone)", q: "一样 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 1,
    zh: "一样", py: "yí yàng", en: "the same",
    why: "Before a 4th tone, 一 becomes 2nd tone: yí yàng." },

  // --- 都 / 也 (appended: “I like both”) ---
  { set: "ADV", frame: "“Coffee and tea — I like both.”", q: "咖啡和茶，我 ___ 喜欢。", opts: ["都 dōu", "也 yě"], a: 0,
    zh: "咖啡和茶，我都喜欢。", py: "kā fēi hé chá, wǒ dōu xǐ huan.", en: "Coffee and tea — I like both.",
    why: "都 sums up the things just listed, and sits right before the verb: 我都喜欢." },

  // --- 那 vs 哪 ---
  { set: "NA_NA", frame: "Pointing at a photo…", q: "___ 个人是我哥哥。", opts: ["那 nà", "哪 nǎ"], a: 0,
    zh: "那个人是我哥哥。", py: "nà ge rén shì wǒ gē ge.", en: "That person is my older brother.",
    why: "A statement pointing someone out — 那, falling 4th tone." },
  { set: "NA_NA", frame: "Asking which one…", q: "___ 个人是你妈妈？", opts: ["那 nà", "哪 nǎ"], a: 1,
    zh: "哪个人是你妈妈？", py: "nǎ ge rén shì nǐ mā ma?", en: "Which person is your mom?",
    why: "A question — 哪, 3rd tone." },
  { set: "NA_NA", frame: "Asking someone's nationality…", q: "你是 ___ 国人？", opts: ["那 nà", "哪 nǎ"], a: 1,
    zh: "你是哪国人？", py: "nǐ shì nǎ guó rén?", en: "What country are you from?",
    why: "“Which-country person?” — questions take 哪." },
  { set: "NA_NA", frame: "In relaxed speech, the question “which one?” sounds like…", q: "", opts: ["něi ge", "nèi ge"], a: 0,
    zh: "哪个？", py: "něi ge?", en: "Which one?",
    why: "哪 relaxes to něi (3rd tone); nèi (4th tone) is 那 — “that one.”" },

  // --- 还是 vs 或者 ---
  { set: "HAISHI_HUOZHE", frame: "Asking a guest to choose…", q: "你喝茶 ___ 喝咖啡？", opts: ["还是 háishì", "或者 huòzhě"], a: 0,
    zh: "你喝茶还是喝咖啡？", py: "nǐ hē chá hái shì hē kā fēi?", en: "Do you want tea or coffee?",
    why: "A choose-one question — 还是." },
  { set: "HAISHI_HUOZHE", frame: "Stating that either is fine…", q: "咖啡 ___ 茶都可以。", opts: ["还是 háishì", "或者 huòzhě"], a: 1,
    zh: "咖啡或者茶都可以。", py: "kā fēi huò zhě chá dōu kě yǐ.", en: "Coffee or tea — either is fine.",
    why: "A statement, nobody has to pick — 或者. 还是 here would be wrong." },
  { set: "HAISHI_HUOZHE", frame: "Teacher or student?", q: "他是老师 ___ 学生？", opts: ["还是 háishì", "或者 huòzhě"], a: 0,
    zh: "他是老师还是学生？", py: "tā shì lǎo shī hái shì xué shēng?", en: "Is he a teacher or a student?",
    why: "The question mark gives it away — question “or” is 还是." },
  { set: "HAISHI_HUOZHE", frame: "Making a plan…", q: "我们可以今天去 ___ 明天去。", opts: ["还是 háishì", "或者 huòzhě"], a: 1,
    zh: "我们可以今天去或者明天去。", py: "wǒ men kě yǐ jīn tiān qù huò zhě míng tiān qù.", en: "We can go today or tomorrow.",
    why: "Statement — 或者. Swapping in 还是 would turn it into a question." },

  // --- 过生日 ---
  { set: "GUO_BIRTHDAY", frame: "Which question sounds native?", q: "", opts: ["你什么时候过生日？", "你的生日是什么时候？"], a: 0,
    zh: "你什么时候过生日？", py: "nǐ shén me shí hou guò shēng rì?", en: "When is your birthday?",
    why: "Natives ask with 过 — “when do you pass/celebrate your birthday?” The 是-version is textbook-stiff." },
  { set: "GUO_BIRTHDAY", frame: "Answering: my birthday is in October…", q: "我十月 ___ 生日。", opts: ["过 guò", "是 shì"], a: 0,
    zh: "我十月过生日。", py: "wǒ shí yuè guò shēng rì.", en: "My birthday is in October.",
    why: "The answer mirrors the question: 我 + time + 过生日." },
  { set: "GUO_BIRTHDAY", frame: "Asking “when?”…", q: "你 ___ 过生日？", opts: ["什么时候 shénme shíhou", "的时候 de shíhou"], a: 0,
    zh: "你什么时候过生日？", py: "nǐ shén me shí hou guò shēng rì?", en: "When do you celebrate your birthday?",
    why: "什么时候 is the question word “when?”; ……的时候 never asks anything." },
  { set: "GUO_BIRTHDAY", frame: "“When I was five …”", q: "我五岁 ___，很喜欢看电视。", opts: ["什么时候 shénme shíhou", "的时候 de shíhou"], a: 1,
    zh: "我五岁的时候，很喜欢看电视。", py: "wǒ wǔ suì de shí hou, hěn xǐ huan kàn diàn shì.", en: "When I was five, I loved watching TV.",
    why: "Not a question — “when I was five” is 我五岁的时候." },

  // --- 上个 / 这个 / 下个 / 每个 + week ---
  { set: "WEEK", frame: "Last Wednesday…", q: "___ 星期三", opts: ["上个 shàng ge", "下个 xià ge"], a: 0,
    zh: "上个星期三", py: "shàng ge xīng qī sān", en: "last Wednesday",
    why: "上 “above” = earlier — the week above this one on the calendar." },
  { set: "WEEK", frame: "Next Wednesday…", q: "___ 星期三", opts: ["这个 zhè ge", "下个 xià ge"], a: 1,
    zh: "下个星期三", py: "xià ge xīng qī sān", en: "next Wednesday",
    why: "下 “below” = later — the week below this one." },
  { set: "WEEK", frame: "This Wednesday…", q: "___ 星期三", opts: ["这个 zhè ge", "每个 měi ge"], a: 0,
    zh: "这个星期三", py: "zhè ge xīng qī sān", en: "this Wednesday",
    why: "这个 — the week we're in right now." },
  { set: "WEEK", frame: "“I study Chinese every Wednesday.”", q: "我 ___ 星期三都学中文。", opts: ["每个 měi ge", "上个 shàng ge"], a: 0,
    zh: "我每个星期三都学中文。", py: "wǒ měi ge xīng qī sān dōu xué zhōng wén.", en: "I study Chinese every Wednesday.",
    why: "每 “every” — note the backing 都 before the verb." },

  // --- word order ---
  { set: "ORDER", frame: "“Today I'm watching TV at home together with my mom.”", q: "", opts: ["我今天和我妈妈在家一起看电视。", "我看电视今天和我妈妈在家一起。"], a: 0,
    zh: "我今天和我妈妈在家一起看电视。", py: "wǒ jīn tiān hé wǒ mā ma zài jiā yì qǐ kàn diàn shì.", en: "Today I'm watching TV at home together with my mom.",
    why: "Time (今天), companion (和我妈妈), place (在家) and adverb (一起) all line up before the verb 看." },
  { set: "ORDER", frame: "Where does the time word go?", q: "", opts: ["我今天在家看书。", "我在家看书今天。"], a: 0,
    zh: "我今天在家看书。", py: "wǒ jīn tiān zài jiā kàn shū.", en: "Today I'm reading at home.",
    why: "Time words come right after the subject — never at the end, unlike English." },
  { set: "ORDER", frame: "Where does the place go?", q: "", opts: ["我在公司吃饭。", "我吃饭在公司。"], a: 0,
    zh: "我在公司吃饭。", py: "wǒ zài gōng sī chī fàn.", en: "I eat at the office.",
    why: "在 + place sits before the verb — Chinese never says “eat at the office” in that order." },
  { set: "ORDER", frame: "Companion before place…", q: "", opts: ["我和朋友在家学中文。", "我在家学中文和朋友。"], a: 0,
    zh: "我和朋友在家学中文。", py: "wǒ hé péng you zài jiā xué zhōng wén.", en: "I study Chinese at home with a friend.",
    why: "The frame runs: who-with (和朋友), then where (在家), then the verb." },

  // --- times & dates ---
  { set: "TIME_DATE", frame: "Say 2:05…", q: "两点 ___", opts: ["零五 líng wǔ", "五 wǔ"], a: 0,
    zh: "两点零五", py: "liǎng diǎn líng wǔ", en: "2:05",
    why: "After 点 the minutes need at least two syllables — 零五 (or 零五分), never a bare 五." },
  { set: "TIME_DATE", frame: "Say 2:05 pm…", q: "", opts: ["下午两点零五", "两点零五下午"], a: 0,
    zh: "下午两点零五", py: "xià wǔ liǎng diǎn líng wǔ", en: "2:05 in the afternoon",
    why: "Big to small: the part of day (下午) comes before the hour." },
  { set: "TIME_DATE", frame: "July 15, 2026…", q: "", opts: ["2026年7月15日", "15日7月2026年"], a: 0,
    zh: "二〇二六年七月十五日", py: "èr líng èr liù nián qī yuè shí wǔ rì", en: "July 15, 2026",
    why: "Big to small: year, then month, then day." },
  { set: "TIME_DATE", frame: "3:15 — what do people actually say?", q: "", opts: ["三点十五分", "三点一刻"], a: 0,
    zh: "三点十五分", py: "sān diǎn shí wǔ fēn", en: "3:15",
    why: "三点一刻 is correct textbook Chinese, but people rarely say 刻 — 十五分 is what you'll hear." },
];
