// Shared data for usage.html and the SRS app (pages/srs/).
// Extracted verbatim from usage.html.
window.USAGE_DATA = {};

// ----- Drill sets: each has a rule shown after every answer -----
window.USAGE_DATA.sets = [
  { id: "NI_NIN", title: "你 vs 您 — plain vs polite “you”",
    rule: "您 nín is the polite form of 你 nǐ — use it for teachers, bosses, elders and respected strangers; use 你 with friends, family and peers. The polite way to ask a surname is 您贵姓? — the casual way is 你姓什么?" },
  { id: "JI_DUOSHAO", title: "几 vs 多少 — asking “how many”",
    rule: "几 jǐ expects a small answer (under 10) and must be followed by a measure word: 几个人? 多少 duōshao works for any number and the measure word is optional: 多少人? or 多少个人?" },
  { id: "KOU_GE", title: "口 vs 个 — counting people",
    rule: "Counting people with 口 kǒu implies they belong to one family — mouths at one table: 我家有五口人. For people in general use 个: 三个人, 二十个学生." },
  { id: "ZHE_NA", title: "zhè/nà vs zhèi/nèi — textbook vs street",
    rule: "In relaxed speech, 这 before a measure word is usually said zhèi and 那 is nèi: zhèi ge, nèi ge. The dictionary readings zhè / nà are for careful or formal speech — and they're what textbooks print." },
  { id: "ADV", title: "Adverb placement — 都 / 也 before the verb",
    rule: "Adverbs like 都 dōu (all, both) and 也 yě (also) come directly before the verb, never after it: 我们都是学生, 我也是工程师." },
  { id: "YI_TONE", title: "一 tone changes",
    rule: "一 is 1st tone (yī) when counting and in ordinals and dates: 一二三, 第一, 一月. Before a 4th tone it becomes 2nd tone: yí ge. Before a 1st, 2nd or 3rd tone it becomes 4th tone: yì zhāng, yì píng, yì qǐ." },
];

// ----- Drill items -----
// set = SETS id; frame = English context (optional); q = prompt, ___ is the blank;
// opts = choices; a = index of the correct one; zh/py/en = full answer to show & speak.
window.USAGE_DATA.items = [
  // --- 你 vs 您 ---
  { set: "NI_NIN", frame: "Speaking to your teacher…", q: "___ 好！", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "您好！", py: "nín hǎo!", en: "Hello! (polite)",
    why: "Teachers get the respectful 您." },
  { set: "NI_NIN", frame: "Asking your boss's surname…", q: "___ 贵姓？", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "您贵姓？", py: "nín guì xìng?", en: "What is your (honorable) surname?",
    why: "贵姓 is honorific — it pairs with 您, never with plain 你." },
  { set: "NI_NIN", frame: "Chatting with a classmate…", q: "___ 叫什么名字？", opts: ["你 nǐ", "您 nín"], a: 0,
    zh: "你叫什么名字？", py: "nǐ jiào shén me míng zi?", en: "What's your name?",
    why: "Peers get plain 你 — 您 would sound stiff between classmates." },
  { set: "NI_NIN", frame: "Which is the polite way to ask a surname?", q: "", opts: ["您贵姓？", "你姓什么？"], a: 0,
    zh: "您贵姓？", py: "nín guì xìng?", en: "What is your (honorable) surname?",
    why: "您贵姓 is the formal formula; 你姓什么 is the everyday version." },
  { set: "NI_NIN", frame: "Asking an elderly stranger…", q: "请问，___ 是王老师吗？", opts: ["你 nǐ", "您 nín"], a: 1,
    zh: "请问，您是王老师吗？", py: "qǐng wèn, nín shì wáng lǎo shī ma?", en: "Excuse me, are you Teacher Wang?",
    why: "Elders and strangers you respect get 您." },
  { set: "NI_NIN", frame: "Texting a good friend…", q: "___ 好吗？", opts: ["你 nǐ", "您 nín"], a: 0,
    zh: "你好吗？", py: "nǐ hǎo ma?", en: "How are you?",
    why: "Friends get 你 — no ceremony needed." },

  // --- 几 vs 多少 ---
  { set: "JI_DUOSHAO", frame: "Families are small…", q: "你家有 ___ 口人？", opts: ["几 jǐ", "多少 duōshao"], a: 0,
    zh: "你家有几口人？", py: "nǐ jiā yǒu jǐ kǒu rén?", en: "How many people are in your family?",
    why: "A family is fewer than ten people, and the measure word 口 follows — classic 几." },
  { set: "JI_DUOSHAO", frame: "A university has thousands of students…", q: "你们大学有 ___ 学生？", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "你们大学有多少学生？", py: "nǐ men dà xué yǒu duō shao xué shēng?", en: "How many students does your university have?",
    why: "A big number — too big for 几. And notice 多少 goes straight to the noun, no measure word needed." },
  { set: "JI_DUOSHAO", frame: "Which is correct?", q: "", opts: ["几人？", "几个人？"], a: 1,
    zh: "几个人？", py: "jǐ ge rén?", en: "How many people?",
    why: "几 must be followed by a measure word — 几个人, never bare 几人." },
  { set: "JI_DUOSHAO", frame: "Which one can drop the measure word?", q: "", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "多少人？", py: "duō shao rén?", en: "How many people?",
    why: "多少人 and 多少个人 are both fine; 几 always keeps its measure word." },
  { set: "JI_DUOSHAO", frame: "Asking the time…", q: "现在 ___ 点？", opts: ["几 jǐ", "多少 duōshao"], a: 0,
    zh: "现在几点？", py: "xiàn zài jǐ diǎn?", en: "What time is it now?",
    why: "Clock hours run 1–12 — a small number, so it's 几点." },
  { set: "JI_DUOSHAO", frame: "Asking the price of a phone…", q: "这个手机 ___ 钱？", opts: ["几 jǐ", "多少 duōshao"], a: 1,
    zh: "这个手机多少钱？", py: "zhè ge shǒu jī duō shao qián?", en: "How much is this phone?",
    why: "Prices can be any size — 多少钱 is the fixed way to ask “how much.”" },

  // --- 口 vs 个 ---
  { set: "KOU_GE", frame: "Talking about my family…", q: "我家有五 ___ 人。", opts: ["口 kǒu", "个 gè"], a: 0,
    zh: "我家有五口人。", py: "wǒ jiā yǒu wǔ kǒu rén.", en: "There are five people in my family.",
    why: "Family members are counted with 口 — mouths at one table." },
  { set: "KOU_GE", frame: "Talking about my class…", q: "我们班有二十 ___ 学生。", opts: ["口 kǒu", "个 gè"], a: 1,
    zh: "我们班有二十个学生。", py: "wǒ men bān yǒu èr shí ge xué shēng.", en: "There are twenty students in our class.",
    why: "Classmates aren't one family — plain 个." },
  { set: "KOU_GE", frame: "Asking about their family…", q: "他们家有几 ___ 人？", opts: ["口 kǒu", "个 gè"], a: 0,
    zh: "他们家有几口人？", py: "tā men jiā yǒu jǐ kǒu rén?", en: "How many people are in their family?",
    why: "Asking about a household, so 口." },
  { set: "KOU_GE", frame: "Three strangers over there…", q: "那儿有三 ___ 人。", opts: ["口 kǒu", "个 gè"], a: 1,
    zh: "那儿有三个人。", py: "nàr yǒu sān ge rén.", en: "There are three people over there.",
    why: "Random people get 个 — 口 would claim they're one household." },

  // --- zhè/nà vs zhèi/nèi ---
  { set: "ZHE_NA", frame: "Chatting with friends, 这个 usually sounds like…", q: "", opts: ["zhè ge", "zhèi ge"], a: 1,
    zh: "这个", py: "zhèi ge (colloquial)", en: "this one",
    why: "Real-life casual speech favors zhèi before a measure word." },
  { set: "ZHE_NA", frame: "Reading the news aloud, 那个 is read…", q: "", opts: ["nà ge", "nèi ge"], a: 0,
    zh: "那个", py: "nà ge (formal)", en: "that one",
    why: "Careful, formal speech keeps the dictionary reading nà." },
  { set: "ZHE_NA", frame: "Street Mandarin: 那个人 sounds like…", q: "", opts: ["nà ge rén", "nèi ge rén"], a: 1,
    zh: "那个人", py: "nèi ge rén (colloquial)", en: "that person",
    why: "nèi is the everyday spoken form of 那 before a measure word." },
  { set: "ZHE_NA", frame: "Which reading do textbooks print for 这?", q: "", opts: ["zhè", "zhèi"], a: 0,
    zh: "这", py: "zhè (standard)", en: "this",
    why: "zhè is the standard reading; zhèi is the colloquial variant you'll hear on the street." },

  // --- adverb before the verb ---
  { set: "ADV", frame: "“We are all students.”", q: "", opts: ["我们都是学生。", "我们是都学生。"], a: 0,
    zh: "我们都是学生。", py: "wǒ men dōu shì xué shēng.", en: "We are all students.",
    why: "都 sits right before the verb 是." },
  { set: "ADV", frame: "“I am also an engineer.”", q: "", opts: ["我是也工程师。", "我也是工程师。"], a: 1,
    zh: "我也是工程师。", py: "wǒ yě shì gōng chéng shī.", en: "I am also an engineer.",
    why: "也 goes before the verb 是, never after it." },
  { set: "ADV", frame: "“Mom and dad are both teachers.”", q: "", opts: ["爸爸妈妈都是老师。", "爸爸妈妈是都老师。"], a: 0,
    zh: "爸爸妈妈都是老师。", py: "bà ba mā ma dōu shì lǎo shī.", en: "Mom and dad are both teachers.",
    why: "都 before 是. Bonus: 爸爸妈妈 together is the everyday word for “parents.”" },
  { set: "ADV", frame: "“They are all my friends.”", q: "", opts: ["他们是我的都朋友。", "他们都是我的朋友。"], a: 1,
    zh: "他们都是我的朋友。", py: "tā men dōu shì wǒ de péng you.", en: "They are all my friends.",
    why: "都 attaches to the verb, not to the noun." },

  // --- 一 tone changes ---
  { set: "YI_TONE", frame: "一 + 个 gè (4th tone)", q: "一个 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 1,
    zh: "一个", py: "yí ge", en: "one (of something)",
    why: "Before a 4th tone, 一 becomes 2nd tone: yí ge." },
  { set: "YI_TONE", frame: "一 + 张 zhāng (1st tone)", q: "一张 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一张", py: "yì zhāng", en: "a sheet of",
    why: "Before a 1st tone, 一 becomes 4th tone: yì zhāng." },
  { set: "YI_TONE", frame: "一 + 瓶 píng (2nd tone)", q: "一瓶 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一瓶", py: "yì píng", en: "a bottle of",
    why: "Before a 2nd tone, 一 becomes 4th tone: yì píng." },
  { set: "YI_TONE", frame: "一 + 起 qǐ (3rd tone)", q: "一起 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一起", py: "yì qǐ", en: "together",
    why: "Before a 3rd tone, 一 becomes 4th tone: yì qǐ." },
  { set: "YI_TONE", frame: "Counting: 一，二，三", q: "How is 一 said when counting?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "一，二，三", py: "yī, èr, sān", en: "one, two, three",
    why: "Counting keeps the citation reading: 1st tone yī." },
  { set: "YI_TONE", frame: "Ordinal: 第一", q: "第一 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "第一", py: "dì yī", en: "first",
    why: "Ordinals keep 一 in 1st tone: dì yī." },
  { set: "YI_TONE", frame: "Date: 一月", q: "一月 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 0,
    zh: "一月", py: "yī yuè", en: "January",
    why: "Dates and month names keep 一 in 1st tone: yī yuè." },
  { set: "YI_TONE", frame: "一 + 杯 bēi (1st tone)", q: "一杯 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一杯", py: "yì bēi", en: "a cup of",
    why: "Before a 1st tone, 一 becomes 4th tone: yì bēi." },
  { set: "YI_TONE", frame: "一 + 年 nián (2nd tone)", q: "一年 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一年", py: "yì nián", en: "one year",
    why: "Before a 2nd tone, 一 becomes 4th tone: yì nián." },
  { set: "YI_TONE", frame: "一 + 点 diǎn (3rd tone)", q: "一点 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 2,
    zh: "一点", py: "yì diǎn", en: "one o'clock; a little",
    why: "Before a 3rd tone, 一 becomes 4th tone: yì diǎn." },
  { set: "YI_TONE", frame: "一 + 样 yàng (4th tone)", q: "一样 — how is 一 said?", opts: ["yī", "yí", "yì"], a: 1,
    zh: "一样", py: "yí yàng", en: "the same",
    why: "Before a 4th tone, 一 becomes 2nd tone: yí yàng." },
];
